pub(super) fn oracle_operation_request(
    operation_id: &str,
    object_name: &str,
    parameter_json: &str,
) -> String {
    if operation_id.ends_with("index.create") {
        return format!("create index idx_{object_name}_id on {object_name} (id);");
    }

    if operation_id.ends_with("index.drop") {
        return "-- Review before running.\ndrop index index_name;".into();
    }

    if operation_id.ends_with("data.import-export") || operation_id.contains("import-export") {
        return format!(
            "-- Oracle managed-driver CSV transfer for {object_name}.\n-- Export streams every selected row to a temporary local artifact before atomic completion.\n-- Import validates the exact insertable-column header, requires an empty target, and uses array binding in guarded batches."
        );
    }

    if operation_id.ends_with("data.backup-restore") || operation_id.contains("backup-restore") {
        let parameters = serde_json::from_str::<serde_json::Value>(parameter_json)
            .unwrap_or_else(|_| serde_json::json!({}));
        let mode = parameters
            .get("mode")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("backup")
            .to_ascii_lowercase();
        let restoring = matches!(mode.as_str(), "restore" | "recover" | "import");
        let location_key = if restoring {
            "sourcePath"
        } else {
            "targetPath"
        };
        let location = parameters
            .get(location_key)
            .and_then(serde_json::Value::as_str)
            .unwrap_or("DATA_PUMP_DIR:datapadplusplus.dmp");
        let scope = parameters
            .get("dataPumpScope")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("schema");
        let source_schema = parameters
            .get("sourceSchema")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("<source-schema>");
        let target_schema = parameters
            .get("targetSchema")
            .and_then(serde_json::Value::as_str);
        return serde_json::to_string_pretty(&serde_json::json!({
            "workflow": if restoring { "oracle.datapump.restore" } else { "oracle.datapump.backup" },
            "mode": mode,
            "format": "datapump",
            "scope": scope,
            "location": location,
            "sourceSchema": source_schema,
            "targetSchema": target_schema,
            "table": parameters.get("table").or_else(|| parameters.get("tableName")),
            "targetTable": parameters.get("targetTable"),
            "conflictPolicy": "fail",
            "executionGate": {
                "owner": "oracle-managed-sidecar",
                "defaultSupport": "live",
                "requiresConfirmation": true,
                "guards": [
                    "managed Oracle runtime required",
                    "authorized DIRECTORY_OBJECT:dump-file.dmp location",
                    "existing dump artifact conflict rejection",
                    "empty target schema or absent target table",
                    "read-only restore block",
                    "DBMS_DATAPUMP completion state verification",
                    "post-restore object validation"
                ],
                "residualRisk": "Oracle DIRECTORY grants, server storage capacity, and Data Pump role assignment remain administrator-managed"
            }
        }))
        .unwrap_or_else(|_| "{}".into());
    }

    match operation_id.rsplit('.').next().unwrap_or(operation_id) {
        "refresh" => "select owner, object_name, object_type, status from all_objects where rownum <= 500 order by owner, object_type, object_name;".into(),
        "execute" => format!("select * from {object_name} where rownum <= 100;"),
        "explain" => format!("explain plan for select * from {object_name} where rownum <= 100;\nselect * from table(dbms_xplan.display);"),
        "profile" => "select * from table(dbms_xplan.display_cursor(null, null, 'ALLSTATS LAST'));\n-- SQL Monitor when granted:\nselect * from v$sql_monitor where rownum <= 100;".to_string(),
        "create" => format!("create table {object_name} (\n  id number generated by default as identity primary key,\n  created_at timestamp default systimestamp not null\n);"),
        "drop" => format!("-- Review before running.\ndrop table {object_name} purge;"),
        "inspect" => "select * from session_privs;\nselect * from session_roles;\nselect * from user_tab_privs;".into(),
        "metrics" => "select * from v$session where rownum <= 100;\nselect tablespace_name, status from user_tablespaces;\nselect * from table(dbms_xplan.display);".into(),
        _ => format!("-- Oracle {operation_id}\n-- parameters:\n{parameter_json}"),
    }
}
