pub(super) fn oracle_operation_request(
    operation_id: &str,
    object_name: &str,
    parameter_json: &str,
) -> String {
    if operation_id.ends_with("index.create") {
        return format!("create index idx_{object_name}_id on {object_name} (id);");
    }

    if operation_id.ends_with("index.drop") {
        return "-- Review before running.\ndrop index index_name;".into();
    }

    if operation_id.ends_with("data.import-export") || operation_id.contains("import-export") {
        return format!(
            "-- Oracle SQLcl/SQL*Plus CSV export plan.\nset markup csv on\nspool <selected-file>.csv\nselect * from {object_name} fetch first 1000 rows only;\nspool off\n-- Data Pump import/export should be reviewed with DIRECTORY grants, schemas, remap rules, and table filters before execution."
        );
    }

    if operation_id.ends_with("data.backup-restore") || operation_id.contains("backup-restore") {
        return "-- Oracle RMAN backup/restore plan.\n-- Review retention policy, archivelog mode, wallet/TDE state, and recovery target before execution.\nrman target /\nbackup database plus archivelog;\n-- restore database preview requires explicit target time/SCN and mount state validation.".into();
    }

    match operation_id.rsplit('.').next().unwrap_or(operation_id) {
        "refresh" => "select owner, object_name, object_type, status from all_objects where rownum <= 500 order by owner, object_type, object_name;".into(),
        "execute" => format!("select * from {object_name} where rownum <= 100;"),
        "explain" => format!("explain plan for select * from {object_name} where rownum <= 100;\nselect * from table(dbms_xplan.display);"),
        "profile" => "select * from table(dbms_xplan.display_cursor(null, null, 'ALLSTATS LAST'));\n-- SQL Monitor when granted:\nselect * from v$sql_monitor where rownum <= 100;".to_string(),
        "create" => format!("create table {object_name} (\n  id number generated by default as identity primary key,\n  created_at timestamp default systimestamp not null\n);"),
        "drop" => format!("-- Review before running.\ndrop table {object_name} purge;"),
        "inspect" => "select * from session_privs;\nselect * from session_roles;\nselect * from user_tab_privs;".into(),
        "metrics" => "select * from v$session where rownum <= 100;\nselect tablespace_name, status from user_tablespaces;\nselect * from table(dbms_xplan.display);".into(),
        _ => format!("-- Oracle {operation_id}\n-- parameters:\n{parameter_json}"),
    }
}
