use super::super::{manifest_has, operation_manifest};
use crate::domain::models::{AdapterManifest, DatastoreOperationManifest};

pub(super) fn extend(manifest: &AdapterManifest, operations: &mut Vec<DatastoreOperationManifest>) {
    if manifest.family == "search" && manifest_has(manifest, "supports_index_management") {
        operations.extend([
            operation_manifest(
                manifest,
                "index.force-merge",
                "Force Merge",
                "index",
                "costly",
                &["supports_index_management"],
                &["profile", "metrics", "raw"],
                "Preview a guarded Lucene segment force-merge request.",
                true,
            ),
            operation_manifest(
                manifest,
                "index.clear-cache",
                "Clear Cache",
                "index",
                "diagnostic",
                &["supports_index_management"],
                &["metrics", "raw"],
                "Preview clearing index-level query/request caches.",
                false,
            ),
            operation_manifest(
                manifest,
                "index.reindex",
                "Reindex",
                "index",
                "write",
                &["supports_index_management"],
                &["diff", "profile", "raw"],
                "Preview copying documents into a destination index.",
                true,
            ),
            operation_manifest(
                manifest,
                "index.close",
                "Close Index",
                "index",
                "write",
                &["supports_index_management"],
                &["diff", "raw"],
                "Preview closing an index.",
                true,
            ),
            operation_manifest(
                manifest,
                "index.open",
                "Open Index",
                "index",
                "write",
                &["supports_index_management"],
                &["diff", "raw"],
                "Preview opening a closed index.",
                true,
            ),
            operation_manifest(
                manifest,
                "index.put-mapping",
                "Update Mapping",
                "index",
                "write",
                &["supports_index_management"],
                &["schema", "diff", "raw"],
                "Preview updating index mapping fields.",
                true,
            ),
            operation_manifest(
                manifest,
                "index.update-settings",
                "Update Settings",
                "index",
                "write",
                &["supports_index_management"],
                &["schema", "diff", "raw"],
                "Preview updating mutable index settings.",
                true,
            ),
            operation_manifest(
                manifest,
                "alias.put",
                "Add Alias",
                "index",
                "write",
                &["supports_index_management"],
                &["diff", "raw"],
                "Preview adding or updating an index alias.",
                true,
            ),
            operation_manifest(
                manifest,
                "alias.delete",
                "Remove Alias",
                "index",
                "destructive",
                &["supports_index_management"],
                &["diff", "raw"],
                "Preview removing an index alias.",
                true,
            ),
            operation_manifest(
                manifest,
                "lifecycle.explain",
                if manifest.engine == "opensearch" {
                    "Explain ISM"
                } else {
                    "Explain ILM"
                },
                "index",
                "diagnostic",
                &["supports_index_management"],
                &["json", "metrics", "raw"],
                "Preview index lifecycle or state-management status.",
                false,
            ),
            operation_manifest(
                manifest,
                "data-stream.rollover",
                "Rollover Data Stream",
                "index",
                "write",
                &["supports_index_management"],
                &["diff", "raw"],
                "Preview a guarded data-stream rollover request.",
                true,
            ),
            operation_manifest(
                manifest,
                "template.create",
                "Create Template",
                "index",
                "write",
                &["supports_index_management"],
                &["schema", "diff", "raw"],
                "Preview creating or replacing an index or component template.",
                true,
            ),
            operation_manifest(
                manifest,
                "template.delete",
                "Delete Template",
                "index",
                "destructive",
                &["supports_index_management"],
                &["diff", "raw"],
                "Preview deleting an index or component template.",
                true,
            ),
            operation_manifest(
                manifest,
                "pipeline.put",
                "Update Pipeline",
                "schema",
                "write",
                &["supports_index_management"],
                &["schema", "diff", "raw"],
                "Preview creating or updating an ingest pipeline.",
                true,
            ),
            operation_manifest(
                manifest,
                "pipeline.simulate",
                "Simulate Pipeline",
                "schema",
                "diagnostic",
                &["supports_index_management"],
                &["document", "json", "raw"],
                "Preview an ingest pipeline simulation request.",
                false,
            ),
            operation_manifest(
                manifest,
                "lifecycle.put",
                if manifest.engine == "opensearch" {
                    "Update ISM Policy"
                } else {
                    "Update ILM Policy"
                },
                "schema",
                "write",
                &["supports_index_management"],
                &["schema", "diff", "raw"],
                "Preview updating index lifecycle or state-management policy.",
                true,
            ),
        ]);
    }

    if manifest.family == "search" && manifest_has(manifest, "supports_query_profile") {
        operations.extend([
                operation_manifest(
                    manifest,
                    "task.cancel",
                    "Cancel Task",
                    "query",
                    "write",
                    &["supports_query_profile"],
                    &["diff", "raw"],
                    "Preview canceling a running search cluster task.",
                    true,
                ),
                operation_manifest(
                    manifest,
                    "diagnostics.slow-log",
                    "Slow Log Plan",
                    "cluster",
                    "diagnostic",
                    &["supports_query_profile"],
                    &["metrics", "table", "json", "raw"],
                    "Plan slow-log settings, search counters, and index-level query/indexing diagnostics.",
                    false,
                ),
                operation_manifest(
                    manifest,
                    "diagnostics.allocation",
                    "Allocation Explain",
                    "cluster",
                    "diagnostic",
                    &["supports_query_profile"],
                    &["table", "json", "raw"],
                    "Plan shard allocation explain and cat-shards requests with cluster-health context.",
                    false,
                ),
            ]);
    }

    if manifest.family == "search" && manifest_has(manifest, "supports_backup_restore") {
        operations.push(operation_manifest(
            manifest,
            "snapshot.restore",
            "Restore Snapshot",
            "connection",
            "destructive",
            &["supports_backup_restore"],
            &["diff", "raw"],
            "Preview restoring a snapshot into the cluster.",
            true,
        ));
    }
}
