/**
 * Datastore families share vocabulary, not behavior selection.
 *
 * Each concrete workbench slice opts into the applicable kinds when it composes
 * its Explorer provider. These lists give live leaf nodes a real inspection
 * provider even when they are not part of the static navigation manifest.
 */
export const RELATIONAL_EXPLORER_INSPECTION_KINDS = [
  'database',
  'schema',
  'table',
  'view',
  'materialized-view',
  'index',
  'function',
  'procedure',
  'routine',
  'sequence',
  'type',
  'extension',
  'columns',
  'constraint',
  'constraints',
  'trigger',
  'statistics',
  'permissions',
  'ddl',
  'synonym',
  'event',
  'user',
  'role',
  'grant',
  'session',
  'lock',
  'wait',
  'statement',
  'job',
  'node',
  'range',
  'region',
  'certificate',
  'zone-configuration',
  'transaction',
  'contention',
  'setting',
  'full-text',
  'service-broker',
  'agent',
  'replication',
  'cdc',
  'storage',
  'server-object',
  'availability-group',
  'extended-event',
  'tablespace',
  'package',
  'json-collection',
  'xml-object',
  'external-table',
  'database-link',
  'queue',
  'scheduler',
  'data-guard',
  'rac',
  'flashback',
] as const

export const EMBEDDED_ANALYTICS_EXPLORER_INSPECTION_KINDS = [
  ...RELATIONAL_EXPLORER_INSPECTION_KINDS,
  'catalog',
  'attached-database',
  'file',
  'pragma',
  'diagnostic',
] as const

export const DOCUMENT_EXPLORER_INSPECTION_KINDS = [
  'account',
  'region',
  'database',
  'collection',
  'view',
  'container',
  'item',
  'index',
  'partition-key',
  'indexing-policy',
  'throughput',
  'change-feed',
  'stored-procedure',
  'trigger',
  'udf',
  'conflict',
  'file',
  'pragma',
  'maintenance',
  'diagnostic',
] as const

export const KEY_VALUE_EXPLORER_INSPECTION_KINDS = [
  'database',
  'key',
  'string',
  'hash',
  'list',
  'set',
  'sorted-set',
  'zset',
  'stream',
  'json',
  'timeseries',
  'bloom',
  'search-index',
  'vector-index',
  'vectorset',
  'channel',
  'script',
  'function',
  'acl-user',
  'memory',
  'slowlog',
  'latency',
  'client',
  'cluster-node',
  'sentinel',
  'replication',
  'persistence',
  'file',
  'metadata',
  'metric',
  'stat',
  'slab',
  'item-class',
  'setting',
  'connection',
  'eviction',
] as const

export const WIDE_COLUMN_EXPLORER_INSPECTION_KINDS = [
  'cluster',
  'node',
  'keyspace',
  'table',
  'view',
  'index',
  'key-schema',
  'type',
  'function',
  'aggregate',
  'permission',
  'policy',
  'replication',
  'repair',
  'compaction',
  'trace',
  'statistics',
  'capacity',
  'stream',
  'backup',
  'alarm',
  'hot-partition',
] as const

export const SEARCH_EXPLORER_INSPECTION_KINDS = [
  'cluster',
  'health',
  'node',
  'shard',
  'index',
  'data-stream',
  'alias',
  'template',
  'pipeline',
  'mapping',
  'user',
  'role',
  'api-key',
  'segment',
  'task',
  'snapshot',
  'lifecycle-policy',
] as const

export const TIME_SERIES_EXPLORER_INSPECTION_KINDS = [
  'organization',
  'bucket',
  'measurement',
  'tag',
  'field',
  'retention-policy',
  'task',
  'authorization',
  'metric',
  'label',
  'target',
  'rule',
  'alert',
  'service-discovery',
  'series',
  'tsdb',
  'aggregator',
  'downsampler',
  'uid',
  'tree',
  'stat',
] as const

export const GRAPH_EXPLORER_INSPECTION_KINDS = [
  'database',
  'graph',
  'node-label',
  'relationship',
  'relationship-type',
  'property-key',
  'index',
  'constraint',
  'procedure',
  'user',
  'permission',
  'transaction',
  'cluster-status',
  'loader-job',
  'collection',
  'edge-collection',
  'view',
  'analyzer',
  'job',
  'schema-status',
  'backend',
  'management-state',
] as const

export const WAREHOUSE_EXPLORER_INSPECTION_KINDS = [
  'project',
  'database',
  'schema',
  'dataset',
  'table',
  'view',
  'materialized-view',
  'external-table',
  'routine',
  'model',
  'stage',
  'file-format',
  'pipe',
  'stream',
  'task',
  'warehouse',
  'share',
  'user',
  'role',
  'job',
  'reservation',
  'dictionary',
  'function',
  'cluster',
  'replica',
  'part',
  'merge',
  'mutation',
  'quota',
] as const
