fn rust_project_files(spec: &ProjectExportSpec) -> Vec<ProjectFile> {
    let root = safe_file_stem(&spec.project_name);
    let mut files = vec![
        project_file(&root, "Cargo.toml", rust_cargo_toml(spec)),
        project_file(&root, ".env.example", env_example(spec)),
        project_file(&root, "README.md", project_readme(spec)),
        project_file(&root, "datapad-api-export.json", project_manifest(spec)),
        project_file(&root, "src/models.rs", rust_models(spec)),
        project_file(&root, "src/repository.rs", rust_repository(spec)),
        project_file(&root, "src/main.rs", rust_main(spec)),
    ];
    if spec.protocol == "grpc" {
        files.push(project_file(&root, "build.rs", rust_grpc_build_rs()));
        files.push(project_file(
            &root,
            "proto/datapad_api.proto",
            grpc_proto(spec),
        ));
    }
    files
}

fn dotnet_project_files(spec: &ProjectExportSpec) -> Vec<ProjectFile> {
    let root = safe_file_stem(&spec.project_name);
    let mut files = vec![
        project_file(
            &root,
            &format!("{}.csproj", spec.project_name),
            dotnet_csproj(spec),
        ),
        project_file(&root, ".env.example", env_example(spec)),
        project_file(&root, "README.md", project_readme(spec)),
        project_file(&root, "datapad-api-export.json", project_manifest(spec)),
        project_file(&root, "Program.cs", dotnet_program(spec)),
        project_file(&root, "Models.cs", dotnet_models(spec)),
        project_file(&root, "DatastoreRepository.cs", dotnet_repository(spec)),
    ];
    if spec.protocol == "graphql" {
        files.push(project_file(
            &root,
            "GraphQlTypes.cs",
            dotnet_graphql_types(spec),
        ));
    }
    if spec.protocol == "grpc" {
        files.push(project_file(
            &root,
            "Services.cs",
            dotnet_grpc_services(spec),
        ));
        files.push(project_file(
            &root,
            "Protos/datapad_api.proto",
            grpc_proto(spec),
        ));
    }
    files
}

fn project_file(root: &str, path: &str, contents: String) -> ProjectFile {
    ProjectFile {
        path: format!("{root}/{path}"),
        contents,
    }
}

fn env_example(spec: &ProjectExportSpec) -> String {
    let mut lines = vec![
        "# Generated by DataPad++ API Server export.".to_string(),
        "# Fill this with your own runtime values before hosting.".to_string(),
        format!("{}=", spec.env_var),
    ];
    if spec.provider == ExportProvider::DynamoDb {
        lines.push("DYNAMODB_ENDPOINT=".into());
    }
    lines.push("ASPNETCORE_URLS=http://localhost:8080".into());
    lines.push("RUST_LOG=info".into());
    format!("{}\n", lines.join("\n"))
}

fn project_readme(spec: &ProjectExportSpec) -> String {
    let resource_lines = if spec.resources.is_empty() {
        "- No CRUD resources exported.\n".into()
    } else {
        spec.resources
            .iter()
            .map(|resource| {
                format!(
                    "- `{}` -> `{}` ({})\n",
                    resource.label, resource.endpoint_path, resource.schema_source_label
                )
            })
            .collect::<String>()
    };
    let warnings = if spec.warnings.is_empty() {
        "No export warnings were generated.\n".into()
    } else {
        spec.warnings
            .iter()
            .map(|warning| format!("- {warning}\n"))
            .collect::<String>()
    };
    format!(
        "# {}\n\nGenerated from a DataPad++ API Server configuration.\n\n- Framework: {}\n- Protocol: {}\n- Datastore: {} / {}\n- Base path: `{}`\n- Configuration: set `{}` in your environment.\n\n## Resources\n\n{}## Export Warnings\n\n{}## Notes\n\nThis export contains typed models and endpoint scaffolding only. DataPad++ does not export secrets. Review the repository implementation and connect it to your production datastore before hosting.\n",
        spec.project_name,
        spec.framework,
        spec.protocol,
        spec.connection_engine,
        spec.connection_family,
        if spec.base_path.is_empty() { "/" } else { &spec.base_path },
        spec.env_var,
        resource_lines,
        warnings
    )
}

fn project_manifest(spec: &ProjectExportSpec) -> String {
    let resources = spec
        .resources
        .iter()
        .map(|resource| {
            json!({
                "label": resource.label,
                "kind": resource.kind,
                "endpointSlug": resource.endpoint_slug,
                "endpointPath": resource.endpoint_path,
                "modelName": resource.model_name,
                "schemaSource": resource.schema_source,
                "schemaSourceLabel": resource.schema_source_label,
                "primaryFields": resource.primary_fields,
                "fields": resource.fields.iter().map(|field| {
                    json!({
                        "name": field.source_name,
                        "dataType": field.data_type,
                        "nullable": field.nullable,
                        "primary": field.primary
                    })
                }).collect::<Vec<_>>()
            })
        })
        .collect::<Vec<_>>();
    serde_json::to_string_pretty(&json!({
        "generatedBy": "DataPad++",
        "framework": spec.framework,
        "protocol": spec.protocol,
        "projectName": spec.project_name,
        "namespace": spec.namespace,
        "packageName": spec.package_name,
        "datastore": {
            "engine": spec.connection_engine,
            "family": spec.connection_family,
            "provider": provider_label(spec.provider)
        },
        "resources": resources,
        "customEndpoints": spec.custom_endpoints.iter().map(|endpoint| {
            json!({
                "label": endpoint.label,
                "method": endpoint.method,
                "endpointPath": endpoint.endpoint_path,
                "parameters": endpoint.parameters.iter().map(|parameter| {
                    json!({
                        "name": parameter.name,
                        "rustType": parameter.rust_type,
                        "csharpType": parameter.csharp_type,
                        "required": parameter.required
                    })
                }).collect::<Vec<_>>()
            })
        }).collect::<Vec<_>>(),
        "warnings": spec.warnings
    }))
    .unwrap_or_else(|_| "{}".into())
}

fn rust_cargo_toml(spec: &ProjectExportSpec) -> String {
    let mut dependencies = vec![
        "axum = \"0.8\"",
        "serde = { version = \"1\", features = [\"derive\"] }",
        "serde_json = \"1\"",
        "tokio = { version = \"1\", features = [\"macros\", \"rt-multi-thread\", \"net\"] }",
        "tracing = \"0.1\"",
        "tracing-subscriber = { version = \"0.3\", features = [\"env-filter\"] }",
    ];
    if spec.protocol == "graphql" {
        dependencies.push("async-graphql = \"7\"");
        dependencies.push("async-graphql-axum = \"7\"");
    }
    if spec.protocol == "grpc" {
        dependencies.push("prost = \"0.13\"");
        dependencies.push("tonic = \"0.12\"");
    }
    match spec.provider {
        ExportProvider::DynamoDb => {
            dependencies.push("aws-config = \"1\"");
            dependencies.push("aws-sdk-dynamodb = \"1\"");
        }
        ExportProvider::LiteDb => {}
        ExportProvider::MongoDb => dependencies.push("mongodb = \"3\""),
        ExportProvider::Redis => dependencies.push("redis = { version = \"0.27\", features = [\"tokio-comp\"] }"),
        ExportProvider::Search => dependencies.push("reqwest = { version = \"0.12\", features = [\"json\"] }"),
        ExportProvider::Sql => dependencies.push("sqlx = { version = \"0.8\", default-features = false, features = [\"runtime-tokio-rustls\", \"sqlite\", \"postgres\", \"mysql\", \"json\"] }"),
    }
    let build_dependencies = if spec.protocol == "grpc" {
        "\n[build-dependencies]\ntonic-build = \"0.12\"\n"
    } else {
        ""
    };
    format!(
        "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\n{}\n{}",
        spec.package_name,
        dependencies.join("\n"),
        build_dependencies
    )
}

fn rust_models(spec: &ProjectExportSpec) -> String {
    let mut output = String::from("use serde::{Deserialize, Serialize};\n\n");
    for resource in &spec.resources {
        if spec.protocol == "graphql" {
            output.push_str("#[derive(Debug, Clone, Default, Serialize, Deserialize, async_graphql::SimpleObject, async_graphql::InputObject)]\n");
            output.push_str(&format!(
                "#[graphql(input_name = \"{}Input\")]\n",
                resource.model_name
            ));
        } else {
            output.push_str("#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n");
        }
        output.push_str(&format!("pub struct {} {{\n", resource.model_name));
        for field in &resource.fields {
            output.push_str(&format!(
                "    #[serde(rename = {})]\n    pub {}: {},\n",
                rust_string_literal(&field.json_name),
                rust_field_name(field),
                field.rust_type
            ));
        }
        output.push_str("}\n\n");
    }
    output
}

fn rust_repository(spec: &ProjectExportSpec) -> String {
    let mut output = format!(
        "use crate::models::*;\nuse serde_json::{{json, Value}};\n\n#[derive(Clone)]\npub struct DatastoreRepository {{\n    connection_string: String,\n}}\n\nimpl DatastoreRepository {{\n    pub fn from_env() -> Self {{\n        let connection_string = std::env::var({}).unwrap_or_default();\n        Self {{ connection_string }}\n    }}\n\n    pub fn connection_configured(&self) -> bool {{\n        !self.connection_string.trim().is_empty()\n    }}\n",
        rust_string_literal(&spec.env_var)
    );
    for resource in &spec.resources {
        let fn_base = snake_case(&resource.endpoint_slug);
        output.push_str(&format!(
            "\n    pub async fn search_{fn_base}(&self, _limit: u32) -> Result<Vec<{}>, String> {{\n        let _ = self.connection_configured();\n        Ok(Vec::new())\n    }}\n\n    pub async fn get_{fn_base}(&self, _identity: String) -> Result<Option<{}>, String> {{\n        let _ = self.connection_configured();\n        Ok(None)\n    }}\n\n    pub async fn create_{fn_base}(&self, values: {}) -> Result<{}, String> {{\n        let _ = self.connection_configured();\n        Ok(values)\n    }}\n\n    pub async fn update_{fn_base}(&self, _identity: String, values: {}) -> Result<{}, String> {{\n        let _ = self.connection_configured();\n        Ok(values)\n    }}\n\n    pub async fn delete_{fn_base}(&self, identity: String) -> Result<Value, String> {{\n        let _ = self.connection_configured();\n        Ok(json!({{ \"deleted\": true, \"identity\": identity }}))\n    }}\n",
            resource.model_name,
            resource.model_name,
            resource.model_name,
            resource.model_name,
            resource.model_name,
            resource.model_name
        ));
    }
    for endpoint in &spec.custom_endpoints {
        output.push_str(&format!(
            "\n    pub async fn run_{}(&self, parameters: Value) -> Result<Value, String> {{\n        let _ = self.connection_configured();\n        Ok(json!({{ \"parameters\": parameters, \"data\": [] }}))\n    }}\n",
            endpoint.function_name
        ));
    }
    output.push_str("}\n");
    output
}

fn rust_main(spec: &ProjectExportSpec) -> String {
    match spec.protocol.as_str() {
        "graphql" => rust_graphql_main(spec),
        "grpc" => rust_grpc_main(spec),
        _ => rust_rest_main(spec),
    }
}

fn rust_rest_main(spec: &ProjectExportSpec) -> String {
    let mut routes = String::new();
    let mut handlers = String::new();
    for resource in &spec.resources {
        let fn_base = snake_case(&resource.endpoint_slug);
        routes.push_str(&format!(
            "        .route({}, get(search_{fn_base}).post(create_{fn_base}))\n        .route({}, get(get_{fn_base}).patch(update_{fn_base}).delete(delete_{fn_base}))\n",
            rust_string_literal(&resource.endpoint_path),
            rust_string_literal(&format!("{}/{{identity}}", resource.endpoint_path))
        ));
        handlers.push_str(&rust_rest_handlers(resource, &fn_base));
    }
    for endpoint in &spec.custom_endpoints {
        let method = if endpoint.method == "POST" {
            "post"
        } else {
            "get"
        };
        routes.push_str(&format!(
            "        .route({}, {method}(run_{}))\n",
            rust_string_literal(&endpoint.endpoint_path),
            endpoint.function_name
        ));
        handlers.push_str(&rust_custom_endpoint_handler(endpoint));
    }
    format!(
        "mod models;\nmod repository;\n\nuse std::{{collections::HashMap, net::SocketAddr, sync::Arc}};\nuse axum::{{extract::{{Path, Query, State}}, http::StatusCode, response::IntoResponse, routing::{{delete, get, patch, post}}, Json, Router}};\nuse serde::Deserialize;\nuse serde_json::{{json, Value}};\nuse models::*;\nuse repository::DatastoreRepository;\n\n#[derive(Clone)]\nstruct AppState {{\n    repository: Arc<DatastoreRepository>,\n}}\n\n#[derive(Deserialize)]\nstruct SearchQuery {{\n    limit: Option<u32>,\n}}\n\n#[derive(Deserialize)]\nstruct MutationBody<T> {{\n    identity: Option<Value>,\n    values: Option<T>,\n    changes: Option<Vec<Value>>,\n    #[serde(rename = \"confirmationText\")]\n    confirmation_text: Option<String>,\n}}\n\n#[tokio::main]\nasync fn main() {{\n    tracing_subscriber::fmt().with_env_filter(tracing_subscriber::EnvFilter::from_default_env()).init();\n    let state = AppState {{ repository: Arc::new(DatastoreRepository::from_env()) }};\n    let app = Router::new()\n{routes}        .route(\"/health\", get(health))\n        .with_state(state);\n    let addr = SocketAddr::from(([0, 0, 0, 0], 8080));\n    let listener = tokio::net::TcpListener::bind(addr).await.expect(\"bind API listener\");\n    axum::serve(listener, app).await.expect(\"serve API\");\n}}\n\nasync fn health(State(state): State<AppState>) -> Json<Value> {{\n    Json(json!({{ \"ok\": true, \"datastoreConfigured\": state.repository.connection_configured() }}))\n}}\n\nfn api_error(error: String) -> (StatusCode, Json<Value>) {{\n    (StatusCode::INTERNAL_SERVER_ERROR, Json(json!({{ \"error\": error }})))\n}}\n\n{handlers}",
    )
}

fn rust_rest_handlers(resource: &ProjectResourceModel, fn_base: &str) -> String {
    format!(
        "async fn search_{fn_base}(State(state): State<AppState>, Query(query): Query<SearchQuery>) -> Result<Json<Vec<{}>>, (StatusCode, Json<Value>)> {{\n    state.repository.search_{fn_base}(query.limit.unwrap_or(100)).await.map(Json).map_err(api_error)\n}}\n\nasync fn get_{fn_base}(State(state): State<AppState>, Path(identity): Path<String>) -> Result<Json<Option<{}>>, (StatusCode, Json<Value>)> {{\n    state.repository.get_{fn_base}(identity).await.map(Json).map_err(api_error)\n}}\n\nasync fn create_{fn_base}(State(state): State<AppState>, Json(body): Json<MutationBody<{}>>) -> Result<Json<{}>, (StatusCode, Json<Value>)> {{\n    let values = body.values.unwrap_or_default();\n    state.repository.create_{fn_base}(values).await.map(Json).map_err(api_error)\n}}\n\nasync fn update_{fn_base}(State(state): State<AppState>, Path(identity): Path<String>, Json(body): Json<MutationBody<{}>>) -> Result<Json<{}>, (StatusCode, Json<Value>)> {{\n    let values = body.values.unwrap_or_default();\n    state.repository.update_{fn_base}(identity, values).await.map(Json).map_err(api_error)\n}}\n\nasync fn delete_{fn_base}(State(state): State<AppState>, Path(identity): Path<String>) -> Result<Json<Value>, (StatusCode, Json<Value>)> {{\n    state.repository.delete_{fn_base}(identity).await.map(Json).map_err(api_error)\n}}\n\n",
        resource.model_name,
        resource.model_name,
        resource.model_name,
        resource.model_name,
        resource.model_name,
        resource.model_name
    )
}

fn rust_custom_endpoint_handler(endpoint: &ProjectCustomEndpoint) -> String {
    if endpoint.method == "POST" {
        format!(
            "async fn run_{}(State(state): State<AppState>, Json(body): Json<Value>) -> Result<Json<Value>, (StatusCode, Json<Value>)> {{\n    state.repository.run_{}(body).await.map(Json).map_err(api_error)\n}}\n\n",
            endpoint.function_name, endpoint.function_name
        )
    } else {
        format!(
            "async fn run_{}(State(state): State<AppState>, Query(query): Query<HashMap<String, String>>) -> Result<Json<Value>, (StatusCode, Json<Value>)> {{\n    state.repository.run_{}(json!(query)).await.map(Json).map_err(api_error)\n}}\n\n",
            endpoint.function_name, endpoint.function_name
        )
    }
}

fn rust_graphql_main(spec: &ProjectExportSpec) -> String {
    let mut query_methods = String::new();
    let mut mutation_methods = String::new();
    for resource in &spec.resources {
        let fn_base = snake_case(&resource.endpoint_slug);
        query_methods.push_str(&format!(
            "    async fn {fn_base}(&self, ctx: &async_graphql::Context<'_>, limit: Option<i32>) -> async_graphql::Result<Vec<{}>> {{\n        let repo = ctx.data::<std::sync::Arc<DatastoreRepository>>()?;\n        Ok(repo.search_{fn_base}(limit.unwrap_or(100).max(1) as u32).await?)\n    }}\n\n",
            resource.model_name
        ));
        mutation_methods.push_str(&format!(
            "    async fn create_{fn_base}(&self, ctx: &async_graphql::Context<'_>, values: {}) -> async_graphql::Result<{}> {{\n        let repo = ctx.data::<std::sync::Arc<DatastoreRepository>>()?;\n        Ok(repo.create_{fn_base}(values).await?)\n    }}\n\n",
            resource.model_name, resource.model_name
        ));
    }
    format!(
        "mod models;\nmod repository;\n\nuse std::sync::Arc;\nuse async_graphql::{{EmptySubscription, Object, Schema}};\nuse async_graphql_axum::GraphQL;\nuse axum::{{response::Html, routing::get, Router}};\nuse models::*;\nuse repository::DatastoreRepository;\n\nstruct QueryRoot;\n\n#[Object]\nimpl QueryRoot {{\n{query_methods}}}\n\nstruct MutationRoot;\n\n#[Object]\nimpl MutationRoot {{\n{mutation_methods}}}\n\n#[tokio::main]\nasync fn main() {{\n    tracing_subscriber::fmt().with_env_filter(tracing_subscriber::EnvFilter::from_default_env()).init();\n    let repository = Arc::new(DatastoreRepository::from_env());\n    let schema = Schema::build(QueryRoot, MutationRoot, EmptySubscription).data(repository).finish();\n    let app = Router::new()\n        .route(\"/\", get(|| async {{ Html(\"GraphQL endpoint: /graphql\") }}))\n        .route(\"/graphql\", get(GraphQL::new(schema.clone())).post(GraphQL::new(schema)));\n    let listener = tokio::net::TcpListener::bind(\"0.0.0.0:8080\").await.expect(\"bind API listener\");\n    axum::serve(listener, app).await.expect(\"serve API\");\n}}\n"
    )
}

fn rust_grpc_main(spec: &ProjectExportSpec) -> String {
    let mut services = String::new();
    let mut add_services = String::new();
    for resource in &spec.resources {
        let service = format!("{}Service", resource.model_name);
        let module = snake_case(&service);
        let server = format!("{}Server", service);
        services.push_str(&format!(
            "#[derive(Default)]\npub struct {service}Impl;\n\n#[tonic::async_trait]\nimpl api::{module}_server::{service} for {service}Impl {{\n    async fn search(&self, _request: tonic::Request<api::SearchRequest>) -> Result<tonic::Response<api::JsonResponse>, tonic::Status> {{\n        Ok(tonic::Response::new(api::JsonResponse {{ json: \"[]\".into() }}))\n    }}\n}}\n\n"
        ));
        add_services.push_str(&format!(
            "        .add_service(api::{module}_server::{server}::new({service}Impl::default()))\n"
        ));
    }
    format!(
        "pub mod api {{ tonic::include_proto!(\"datapad.api\"); }}\n\n{services}#[tokio::main]\nasync fn main() -> Result<(), Box<dyn std::error::Error>> {{\n    tracing_subscriber::fmt().with_env_filter(tracing_subscriber::EnvFilter::from_default_env()).init();\n    tonic::transport::Server::builder()\n{add_services}        .serve(\"0.0.0.0:8080\".parse()?)\n        .await?;\n    Ok(())\n}}\n"
    )
}

fn rust_grpc_build_rs() -> String {
    "fn main() -> Result<(), Box<dyn std::error::Error>> {\n    tonic_build::compile_protos(\"proto/datapad_api.proto\")?;\n    Ok(())\n}\n".into()
}

fn dotnet_csproj(spec: &ProjectExportSpec) -> String {
    let mut packages = vec![
        "    <PackageReference Include=\"Microsoft.AspNetCore.OpenApi\" Version=\"10.0.0\" />",
    ];
    if spec.protocol == "graphql" {
        packages.push(
            "    <PackageReference Include=\"HotChocolate.AspNetCore\" Version=\"15.1.11\" />",
        );
    }
    if spec.protocol == "grpc" {
        packages.push("    <PackageReference Include=\"Grpc.AspNetCore\" Version=\"2.67.0\" />");
        packages.push("    <PackageReference Include=\"Grpc.Tools\" Version=\"2.67.0\" PrivateAssets=\"All\" />");
    }
    match spec.provider {
        ExportProvider::DynamoDb => packages
            .push("    <PackageReference Include=\"AWSSDK.DynamoDBv2\" Version=\"4.0.3.3\" />"),
        ExportProvider::LiteDb => {
            packages.push("    <PackageReference Include=\"LiteDB\" Version=\"5.0.21\" />")
        }
        ExportProvider::MongoDb => {
            packages.push("    <PackageReference Include=\"MongoDB.Driver\" Version=\"3.4.0\" />")
        }
        ExportProvider::Redis => packages
            .push("    <PackageReference Include=\"StackExchange.Redis\" Version=\"2.8.58\" />"),
        ExportProvider::Search => {}
        ExportProvider::Sql => {
            packages.push("    <PackageReference Include=\"Dapper\" Version=\"2.1.66\" />")
        }
    }
    let proto = if spec.protocol == "grpc" {
        "\n  <ItemGroup>\n    <Protobuf Include=\"Protos\\datapad_api.proto\" GrpcServices=\"Server\" />\n  </ItemGroup>\n"
    } else {
        ""
    };
    format!(
        "<Project Sdk=\"Microsoft.NET.Sdk.Web\">\n  <PropertyGroup>\n    <TargetFramework>net10.0</TargetFramework>\n    <Nullable>enable</Nullable>\n    <ImplicitUsings>enable</ImplicitUsings>\n  </PropertyGroup>\n\n  <ItemGroup>\n{}\n  </ItemGroup>\n{proto}</Project>\n",
        packages.join("\n")
    )
}

fn dotnet_program(spec: &ProjectExportSpec) -> String {
    match spec.protocol.as_str() {
        "graphql" => dotnet_graphql_program(spec),
        "grpc" => dotnet_grpc_program(spec),
        _ => dotnet_rest_program(spec),
    }
}

fn dotnet_rest_program(spec: &ProjectExportSpec) -> String {
    let mut routes = String::new();
    for resource in &spec.resources {
        let base = pascal_case(&resource.endpoint_slug);
        routes.push_str(&format!(
            "api.MapGet({path}, async (DatastoreRepository repo, int? limit) => TypedResults.Ok(await repo.Search{base}Async(limit ?? 100)));\napi.MapGet({identity_path}, async (DatastoreRepository repo, string identity) => TypedResults.Ok(await repo.Get{base}Async(identity)));\napi.MapPost({path}, async (DatastoreRepository repo, MutationBody<{model}> body) => TypedResults.Ok(await repo.Create{base}Async(body.Values ?? new {model}())));\napi.MapPatch({identity_path}, async (DatastoreRepository repo, string identity, MutationBody<{model}> body) => TypedResults.Ok(await repo.Update{base}Async(identity, body.Values ?? new {model}())));\napi.MapDelete({identity_path}, async (DatastoreRepository repo, string identity) => TypedResults.Ok(await repo.Delete{base}Async(identity)));\n",
            path = csharp_string_literal(&resource.endpoint_path),
            identity_path = csharp_string_literal(&format!("{}/{{identity}}", resource.endpoint_path)),
            model = resource.model_name
        ));
    }
    for endpoint in &spec.custom_endpoints {
        let name = pascal_case(&endpoint.function_name);
        if endpoint.method == "POST" {
            routes.push_str(&format!(
                "api.MapPost({path}, async (DatastoreRepository repo, JsonElement body) => TypedResults.Ok(await repo.Run{name}Async(body)));\n",
                path = csharp_string_literal(&endpoint.endpoint_path)
            ));
        } else {
            routes.push_str(&format!(
                "api.MapGet({path}, async (DatastoreRepository repo, HttpRequest request) => TypedResults.Ok(await repo.Run{name}Async(request.Query.ToDictionary(item => item.Key, item => item.Value.ToString()))));\n",
                path = csharp_string_literal(&endpoint.endpoint_path)
            ));
        }
    }
    format!(
        "using System.Text.Json;\nusing Microsoft.AspNetCore.Http.HttpResults;\nusing Microsoft.AspNetCore.Mvc;\n\nvar builder = WebApplication.CreateBuilder(args);\nbuilder.Services.AddOpenApi();\nbuilder.Services.AddSingleton<DatastoreRepository>();\n\nvar app = builder.Build();\nif (app.Environment.IsDevelopment())\n{{\n    app.MapOpenApi();\n}}\n\nvar api = app.MapGroup(\"\");\napi.MapGet(\"/health\", (DatastoreRepository repo) => TypedResults.Ok(new {{ ok = true, datastoreConfigured = repo.ConnectionConfigured }}));\n{routes}\napp.Run();\n\npublic sealed record MutationBody<T>(T? Values, JsonElement? Identity, JsonElement[]? Changes, string? ConfirmationText);\n"
    )
}

fn dotnet_graphql_program(_spec: &ProjectExportSpec) -> String {
    "var builder = WebApplication.CreateBuilder(args);\nbuilder.Services.AddSingleton<DatastoreRepository>();\nbuilder.Services.AddGraphQLServer().AddQueryType<Query>().AddMutationType<Mutation>();\n\nvar app = builder.Build();\napp.MapGraphQL();\napp.Run();\n".into()
}

fn dotnet_grpc_program(spec: &ProjectExportSpec) -> String {
    let services = spec
        .resources
        .iter()
        .map(|resource| format!("app.MapGrpcService<{}ServiceImpl>();", resource.model_name))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "var builder = WebApplication.CreateBuilder(args);\nbuilder.Services.AddGrpc();\nbuilder.Services.AddSingleton<DatastoreRepository>();\n\nvar app = builder.Build();\n{services}\napp.MapGet(\"/\", () => \"gRPC endpoint. Use a gRPC client with Protos/datapad_api.proto.\");\napp.Run();\n"
    )
}

fn dotnet_models(spec: &ProjectExportSpec) -> String {
    let mut output = format!(
        "using System.Text.Json;\nusing System.Text.Json.Serialization;\n\nnamespace {};\n\n",
        spec.namespace
    );
    for resource in &spec.resources {
        output.push_str(&format!(
            "public sealed class {} \n{{\n",
            resource.model_name
        ));
        for field in &resource.fields {
            output.push_str(&format!(
                "    [JsonPropertyName({})]\n    public {} {} {{ get; set; }}{}\n",
                csharp_string_literal(&field.json_name),
                field.csharp_type,
                field.csharp_name,
                csharp_default_value(field)
            ));
        }
        output.push_str("}\n\n");
    }
    output
}

fn dotnet_repository(spec: &ProjectExportSpec) -> String {
    let mut output = format!(
        "using System.Text.Json;\n\nnamespace {};\n\npublic sealed class DatastoreRepository\n{{\n    private readonly string _connectionString;\n\n    public DatastoreRepository(IConfiguration configuration)\n    {{\n        _connectionString = configuration[{}] ?? string.Empty;\n    }}\n\n    public bool ConnectionConfigured => !string.IsNullOrWhiteSpace(_connectionString);\n",
        spec.namespace,
        csharp_string_literal(&spec.env_var)
    );
    for resource in &spec.resources {
        let base = pascal_case(&resource.endpoint_slug);
        output.push_str(&format!(
            "\n    public Task<IReadOnlyList<{model}>> Search{base}Async(int limit)\n    {{\n        _ = limit;\n        return Task.FromResult<IReadOnlyList<{model}>>(Array.Empty<{model}>());\n    }}\n\n    public Task<{model}?> Get{base}Async(string identity)\n    {{\n        _ = identity;\n        return Task.FromResult<{model}?>(null);\n    }}\n\n    public Task<{model}> Create{base}Async({model} values)\n    {{\n        return Task.FromResult(values);\n    }}\n\n    public Task<{model}> Update{base}Async(string identity, {model} values)\n    {{\n        _ = identity;\n        return Task.FromResult(values);\n    }}\n\n    public Task<object> Delete{base}Async(string identity)\n    {{\n        return Task.FromResult<object>(new {{ deleted = true, identity }});\n    }}\n",
            model = resource.model_name
        ));
    }
    for endpoint in &spec.custom_endpoints {
        let name = pascal_case(&endpoint.function_name);
        output.push_str(&format!(
            "\n    public Task<object> Run{name}Async(object parameters)\n    {{\n        return Task.FromResult<object>(new {{ parameters, data = Array.Empty<object>() }});\n    }}\n"
        ));
    }
    output.push_str("}\n");
    output
}

fn dotnet_graphql_types(spec: &ProjectExportSpec) -> String {
    let mut query = format!(
        "namespace {};\n\npublic sealed class Query\n{{\n",
        spec.namespace
    );
    let mut mutation = String::from("public sealed class Mutation\n{\n");
    for resource in &spec.resources {
        let base = pascal_case(&resource.endpoint_slug);
        query.push_str(&format!(
            "    public Task<IReadOnlyList<{model}>> {base}(DatastoreRepository repo, int? limit) => repo.Search{base}Async(limit ?? 100);\n",
            model = resource.model_name
        ));
        mutation.push_str(&format!(
            "    public Task<{model}> Create{base}(DatastoreRepository repo, {model} values) => repo.Create{base}Async(values);\n",
            model = resource.model_name
        ));
    }
    query.push_str("}\n\n");
    mutation.push_str("}\n");
    format!("{query}{mutation}")
}

fn dotnet_grpc_services(spec: &ProjectExportSpec) -> String {
    let mut output = format!(
        "using Grpc.Core;\nusing {}.Grpc;\n\nnamespace {};\n\n",
        spec.namespace, spec.namespace
    );
    for resource in &spec.resources {
        output.push_str(&format!(
            "public sealed class {model}ServiceImpl : {model}Service.{model}ServiceBase\n{{\n    public override Task<JsonResponse> Search(SearchRequest request, ServerCallContext context)\n    {{\n        return Task.FromResult(new JsonResponse {{ Json = \"[]\" }});\n    }}\n}}\n\n",
            model = resource.model_name
        ));
    }
    output
}

fn grpc_proto(spec: &ProjectExportSpec) -> String {
    let mut messages = String::new();
    let mut services = String::new();
    for resource in &spec.resources {
        messages.push_str(&format!("message {} {{\n", resource.model_name));
        for (index, field) in resource.fields.iter().enumerate() {
            messages.push_str(&format!(
                "  {} {} = {};\n",
                proto_type(field),
                snake_case(&field.source_name),
                index + 1
            ));
        }
        messages.push_str("}\n\n");
        services.push_str(&format!(
            "service {}Service {{\n  rpc Search (SearchRequest) returns (JsonResponse);\n}}\n\n",
            resource.model_name
        ));
    }
    format!(
        "syntax = \"proto3\";\n\npackage datapad.api;\noption csharp_namespace = {};\n\nmessage SearchRequest {{\n  uint32 limit = 1;\n}}\n\nmessage JsonResponse {{\n  string json = 1;\n}}\n\n{messages}{services}",
        rust_string_literal(&format!("{}.Grpc", spec.namespace))
    )
}

fn proto_type(field: &ProjectFieldModel) -> &'static str {
    if field.rust_type.contains("i64") {
        "int64"
    } else if field.rust_type.contains("i32") || field.rust_type.contains("i16") {
        "int32"
    } else if field.rust_type.contains("f64") {
        "double"
    } else if field.rust_type.contains("bool") {
        "bool"
    } else {
        "string"
    }
}

fn csharp_default_value(field: &ProjectFieldModel) -> &'static str {
    if field.csharp_type == "string" {
        " = string.Empty;"
    } else if field.csharp_type == "byte[]" {
        " = Array.Empty<byte>();"
    } else {
        ""
    }
}

fn rust_field_name(field: &ProjectFieldModel) -> String {
    if matches!(
        field.rust_name.as_str(),
        "type" | "match" | "ref" | "self" | "crate" | "super" | "mod" | "async" | "await"
    ) {
        format!("{}_", field.rust_name)
    } else {
        field.rust_name.clone()
    }
}

fn rust_string_literal(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "\"\"".into())
}

fn csharp_string_literal(value: &str) -> String {
    format!("@\"{}\"", value.replace('"', "\"\""))
}

fn zip_project_files(files: Vec<ProjectFile>) -> Result<Vec<u8>, CommandError> {
    let cursor = Cursor::new(Vec::new());
    let mut writer = zip::ZipWriter::new(cursor);
    let options = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated);
    for file in files {
        writer.start_file(&file.path, options).map_err(|error| {
            CommandError::new(
                "api-server-export-zip-failed",
                format!("Unable to add `{}` to the project zip: {error}", file.path),
            )
        })?;
        writer
            .write_all(file.contents.as_bytes())
            .map_err(|error| {
                CommandError::new(
                    "api-server-export-zip-failed",
                    format!(
                        "Unable to write `{}` to the project zip: {error}",
                        file.path
                    ),
                )
            })?;
    }
    let cursor = writer.finish().map_err(|error| {
        CommandError::new(
            "api-server-export-zip-failed",
            format!("Unable to finish the project zip: {error}"),
        )
    })?;
    Ok(cursor.into_inner())
}

fn unique_identifier(seen: &mut HashMap<String, usize>, value: String, fallback: &str) -> String {
    let mut value = value.trim_matches('_').to_string();
    if value.is_empty() || value.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        value = format!("{fallback}{value}");
    }
    let count = seen.entry(value.clone()).or_insert(0);
    *count += 1;
    if *count > 1 {
        format!("{value}{count}")
    } else {
        value
    }
}

fn safe_file_stem(value: &str) -> String {
    let stem = value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                ch
            } else {
                '-'
            }
        })
        .collect::<String>()
        .split('-')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("-");
    if stem.is_empty() {
        "api-server".into()
    } else {
        stem
    }
}

fn snake_case(value: &str) -> String {
    let mut result = String::new();
    let mut previous_was_separator = true;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() && !previous_was_separator && !result.ends_with('_') {
                result.push('_');
            }
            result.push(ch.to_ascii_lowercase());
            previous_was_separator = false;
        } else if !result.ends_with('_') {
            result.push('_');
            previous_was_separator = true;
        }
    }
    let result = result.trim_matches('_').to_string();
    if result.is_empty() {
        "value".into()
    } else if result.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        format!("value_{result}")
    } else {
        result
    }
}

fn pascal_case(value: &str) -> String {
    let mut result = String::new();
    for part in value
        .split(|ch: char| !ch.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
    {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_ascii_uppercase());
            for ch in chars {
                result.push(ch.to_ascii_lowercase());
            }
        }
    }
    if result.is_empty() {
        String::new()
    } else if result.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        format!("Value{result}")
    } else {
        result
    }
}

fn api_parameter_names(query_text: &str) -> Vec<String> {
    let mut names = Vec::new();
    let mut offset = 0usize;
    while let Some(start) = query_text[offset..].find("{{api.") {
        let token_start = offset + start + "{{api.".len();
        let Some(end) = query_text[token_start..].find("}}") else {
            break;
        };
        let raw_name = &query_text[token_start..token_start + end];
        if let Some(name) = normalize_api_parameter_name(raw_name) {
            if !names.contains(&name) {
                names.push(name);
            }
        }
        offset = token_start + end + "}}".len();
    }
    names
}

fn normalize_api_parameter_name(value: &str) -> Option<String> {
    let value = value.trim();
    if value.is_empty() {
        return None;
    }
    let mut characters = value.chars();
    let first = characters.next()?;
    if !(first.is_ascii_alphabetic() || first == '_') {
        return None;
    }
    if !characters.all(|character| character.is_ascii_alphanumeric() || character == '_') {
        return None;
    }
    Some(value.to_string())
}

fn api_server_slug(value: &str) -> String {
    let mut output = String::new();
    let mut last_dash = false;
    for character in value.trim().chars() {
        if character.is_ascii_alphanumeric() {
            output.push(character.to_ascii_lowercase());
            last_dash = false;
        } else if !last_dash && !output.is_empty() {
            output.push('-');
            last_dash = true;
        }
    }
    while output.ends_with('-') {
        output.pop();
    }
    if output.is_empty() {
        "resource".into()
    } else {
        output
    }
}

