use super::*;

const OFFICIAL_WEBSITE_URL: &str = "https://datapad-plus-plus.org/";

pub(super) fn env_example(spec: &ProjectExportSpec) -> String {
    let additional = spec
        .additional_configuration
        .iter()
        .map(|(key, value)| format!("{key}={value}\n"))
        .collect::<String>();
    format!(
        "# Generated by DataPad++ API Server export.\n# Supply your own runtime value; no DataPad++ secret is included.\n{}={}\n{}ASPNETCORE_URLS=http://localhost:8080\nRUST_LOG=info\n",
        spec.configuration_key, spec.configuration_example, additional
    )
}

pub(super) fn project_readme(spec: &ProjectExportSpec) -> String {
    let resources = if spec.resources.is_empty() {
        "- No CRUD resources exported.\n".into()
    } else {
        spec.resources
            .iter()
            .map(|resource| {
                format!(
                    "- `{}` -> `{}` ({}; {}){}\n",
                    resource.label,
                    resource.endpoint_path,
                    resource.schema_source_label,
                    resource.mode.id(),
                    resource
                        .capability_reason
                        .as_ref()
                        .map(|reason| format!(" — {reason}"))
                        .unwrap_or_default()
                )
            })
            .collect::<String>()
    };
    let warnings = if spec.warnings.is_empty() {
        "No export warnings were generated.\n".into()
    } else {
        spec.warnings
            .iter()
            .map(|warning| format!("- {warning}\n"))
            .collect::<String>()
    };
    let composite_identities = spec
        .resources
        .iter()
        .filter(|resource| resource.primary_fields.len() > 1)
        .map(|resource| {
            format!(
                "- `{}` uses a URL-encoded JSON identity object with keys: {}.\n",
                resource.endpoint_path,
                resource
                    .primary_fields
                    .iter()
                    .map(|field| format!("`{}`", field.source_name))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        })
        .collect::<String>();
    let document_identities = spec
        .resources
        .iter()
        .filter(|resource| {
            resource.shape.is_document()
                && !resource.primary_fields.is_empty()
                && resource.primary_fields.len() <= 1
        })
        .map(|resource| {
            format!(
                "- `{}` uses `{}` identities.\n",
                resource.endpoint_path, resource.identity_format
            )
        })
        .collect::<String>();
    let identity_lines = format!("{composite_identities}{document_identities}");
    let identity_documentation = if identity_lines.is_empty() {
        String::new()
    } else if document_identities.is_empty() {
        format!("## Composite identities\n\n{identity_lines}\n")
    } else {
        format!("## Resource identities\n\n{identity_lines}\n")
    };
    format!(
        "# {}\n\nGenerated from a DataPad++ API Server configuration.\n\n- DataPad++: [{}]({})\n- Framework: {}\n- Protocol: {}\n- Datastore: {} / {}\n- Data client: {}\n- Adapter: `{}`\n- Base path: `{}`\n- Configuration: set `{}` in your environment. Example format: `{}`.\n\n## Run\n\n1. Copy `.env.example` values into your environment or secret store.\n2. Restore/build the project. The first restore creates the application lockfile; commit it with your project.\n3. Start the API and call `/health` to verify the live datastore connection.\n\n## Resources\n\n{}{}## Export Warnings\n\n{}## Safety\n\nDataPad++ does not export secrets. {}\n",
        spec.project_name,
        OFFICIAL_WEBSITE_URL,
        OFFICIAL_WEBSITE_URL,
        spec.framework,
        spec.protocol,
        spec.connection_engine,
        spec.connection_family,
        spec.client_label,
        spec.adapter_id,
        if spec.base_path.is_empty() {
            "/"
        } else {
            &spec.base_path
        },
        spec.configuration_key,
        spec.configuration_example,
        resources,
        identity_documentation,
        warnings,
        spec.safety_note,
    )
}

pub(super) fn project_manifest(spec: &ProjectExportSpec) -> String {
    let document_export = spec
        .resources
        .iter()
        .any(|resource| resource.shape.is_document());
    let resources = spec
        .resources
        .iter()
        .map(|resource| {
            let mut manifest = json!({
                "id": resource.id,
                "label": resource.label,
                "kind": resource.kind,
                "endpointSlug": resource.endpoint_slug,
                "endpointPath": resource.endpoint_path,
                "modelName": resource.model_name,
                "schemaSource": resource.schema_source,
                "schemaSourceLabel": resource.schema_source_label,
                "database": resource.database_name,
                "schema": resource.schema_name,
                "table": resource.table_name,
                "qualifiedTarget": resource.qualified_target,
                "mode": resource.mode.id(),
                "reason": resource.capability_reason,
                "primaryFields": resource.primary_fields.iter()
                    .map(|field| field.source_name.clone())
                    .collect::<Vec<_>>(),
                "fields": resource.fields.iter().map(|field| json!({
                    "name": field.source_name,
                    "dataType": field.data_type,
                    "nullable": field.nullable,
                    "primary": field.primary,
                    "writable": field.writable
                })).collect::<Vec<_>>()
            });
            if resource.shape.is_document() {
                let object = manifest
                    .as_object_mut()
                    .expect("resource manifest is an object");
                object.insert("resourceShape".into(), json!(resource.shape.id()));
                object.insert("identityFormat".into(), json!(resource.identity_format));
                object.insert("jsonFormat".into(), json!(resource.json_format));
                object.insert("sampleStatus".into(), json!(resource.sample_status));
                object.insert(
                    "identitySchema".into(),
                    json!(resource
                        .primary_fields
                        .iter()
                        .map(|field| json!({
                            "name": field.source_name,
                            "type": field.data_type
                        }))
                        .collect::<Vec<_>>()),
                );
            }
            manifest
        })
        .collect::<Vec<_>>();
    let mut manifest = json!({
        "schemaVersion": 2,
        "generatedBy": "DataPad++",
        "generatedByUrl": OFFICIAL_WEBSITE_URL,
        "framework": spec.framework,
        "protocol": spec.protocol,
        "projectName": spec.project_name,
        "namespace": spec.namespace,
        "packageName": spec.package_name,
        "adapter": {
            "id": spec.adapter_id,
            "client": spec.client_label,
            "configurationKey": spec.configuration_key
        },
        "datastore": {
            "engine": spec.connection_engine,
            "family": spec.connection_family
        },
        "dependencies": spec.dependencies.iter().map(|dependency| json!({
            "package": dependency.package,
            "version": dependency.version,
            "build": dependency.build
        })).collect::<Vec<_>>(),
        "resources": resources,
        "customEndpoints": spec.custom_endpoints.iter().map(|endpoint| json!({
            "id": endpoint.id,
            "label": endpoint.label,
            "method": endpoint.method,
            "endpointPath": endpoint.endpoint_path,
            "sourceQuery": endpoint.original_query,
            "rowLimit": endpoint.row_limit,
            "parameters": endpoint.parameters.iter().map(|parameter| json!({
                "name": parameter.name,
                "type": parameter.parameter_type,
                "required": parameter.required
            })).collect::<Vec<_>>()
        })).collect::<Vec<_>>(),
        "warnings": spec.warnings
    });
    if document_export {
        let compiler_requirements = if spec.framework == "rust" {
            json!({ "rust": spec.rust_version })
        } else {
            json!({ "dotnet": "net10.0" })
        };
        manifest
            .as_object_mut()
            .expect("project manifest is an object")
            .insert("compilerRequirements".into(), compiler_requirements);
    }
    serde_json::to_string_pretty(&manifest).unwrap_or_else(|_| "{}".into())
}

pub(super) fn grpc_proto(spec: &ProjectExportSpec) -> String {
    let services = spec
        .resources
        .iter()
        .map(|resource| {
            format!(
                "service {}Service {{\n  rpc Search (SearchRequest) returns (JsonResponse);\n}}\n",
                resource.model_name
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "syntax = \"proto3\";\n\npackage datapad.api;\noption csharp_namespace = \"{}.Grpc\";\n\nmessage SearchRequest {{\n  uint32 limit = 1;\n}}\n\nmessage JsonResponse {{\n  string json = 1;\n}}\n\n{}",
        spec.namespace, services
    )
}
