import type { DatastoreFeatureBacklogEntry } from '../datastore-roadmap'
import { documentRenderers } from './common'

export const MONGODB_DATASTORE_FEATURE = {
    engine: 'mongodb',
    displayName: 'MongoDB',
    family: 'document',
    maturity: 'mvp',
    defaultLanguage: 'mongodb',
    queryLanguages: ['mongodb', 'json'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'MongoDB wire protocol driver',
      'MongoDB URI connection string with SCRAM/X.509/OIDC options',
    ],
    defaultPort: 27017,
    managementModel: 'BSON document databases with collections, indexes, validators, views, replica/shard topology, users, roles, and privileges.',
    queryModel: 'Visual find/filter builder, aggregation pipeline builder, and raw MongoDB JSON command editor.',
    presentationModel: 'Documents, JSON, inferred tables, collection schemas, explain/profile output, and metrics.',
    securityModel: 'Database users, roles, collection privileges, auth mechanisms, TLS, read-only profiles, and destructive-command guardrails.',
    resultRenderers: [...documentRenderers],
    capabilities: [
      'supports_document_view',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_streaming_results',
      'supports_schema_browser',
      'supports_admin_operations',
      'supports_index_management',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_query_cancellation',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_backup_restore',
      'supports_vector_search',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Database and collection browser',
      'Add/drop collection',
      'Document CRUD and table-style document view',
      'Index CRUD, visual find/filter builder, and aggregation pipeline builder',
    ],
    advancedFeatures: [
      'Explain renderer',
      '$indexStats and query stats panels',
      'Schema inference and validation editor',
      'Shard and replica metrics',
    ],
    diagnosticFeatures: [
      'Winning/rejected plan rendering',
      'Index usage stats',
      'Collection and server metrics',
      'Permission-aware command blocking',
    ],
    analyticsSignals: [
      'Documents examined and returned',
      'Index hit ratio',
      'Collection size and storage size',
      'Replica lag and shard distribution',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const COSMOSDB_DATASTORE_FEATURE = {
    engine: 'cosmosdb',
    displayName: 'Cosmos DB',
    family: 'document',
    maturity: 'beta',
    defaultLanguage: 'sql',
    queryLanguages: ['sql', 'mongodb', 'cql', 'gremlin'],
    connectionModes: ['cloud-iam', 'cloud-sdk', 'connection-string'],
    primaryConnectionMechanisms: [
      'Azure SDK with Entra identity or account keys',
      'API-specific connection strings for SQL, MongoDB, Cassandra, Gremlin, or Table APIs',
    ],
    defaultPort: 443,
    managementModel: 'Managed multi-model accounts with databases, containers, partition keys, indexing policies, throughput, regions, and per-API objects.',
    queryModel: 'SQL API query builder first, then API-specific Mongo/Cassandra/Gremlin/Table adapters.',
    presentationModel: 'JSON documents, tabular projections, RU charge metrics, query metrics, index metrics, latency charts, and partition views.',
    securityModel: 'Azure RBAC, keys, resource tokens, private endpoints, Entra identity, and permission-aware account/container actions.',
    resultRenderers: ['document', 'table', 'json', 'metrics', 'series', 'costEstimate'],
    capabilities: [
      'supports_document_view',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_permission_inspection',
      'supports_cloud_iam',
      'supports_metrics_collection',
      'supports_cost_estimation',
      'supports_import_export',
      'supports_query_profile',
    ],
    baselineFeatures: [
      'Account, database, and container browser',
      'SQL query builder',
      'Partition key and indexing policy viewer',
      'Document/item browser with export',
    ],
    advancedFeatures: [
      'RU charge and query metrics',
      'Index metrics and latency charts',
      'Partition, RU, indexing, and global distribution panels',
      'Guarded throughput, consistency, and failover previews',
      'Per-API adapters',
      'Throughput and region dashboards',
    ],
    diagnosticFeatures: [
      'RU and latency panels',
      'Cross-partition query warnings',
      'Index utilization reporting',
      'Azure RBAC explanations',
    ],
    analyticsSignals: [
      'RU charge',
      'Request latency',
      'Document count and storage',
      'Throttles and region failover events',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const LITEDB_DATASTORE_FEATURE = {
    engine: 'litedb',
    displayName: 'LiteDB',
    family: 'document',
    maturity: 'beta',
    defaultLanguage: 'json',
    queryLanguages: ['json'],
    connectionModes: ['local-file', 'connection-string'],
    primaryConnectionMechanisms: [
      'Local LiteDB file',
      '.NET LiteDB connection string with optional password',
    ],
    managementModel: 'Embedded .NET document database with collections, BSON documents, indexes, file passwords, and local storage management.',
    queryModel: 'Collection query editor, visual filter builder, and raw JSON query document.',
    presentationModel: 'Documents, tabular projections, collection/index metadata, raw JSON, and import/export files.',
    securityModel: 'Local file permissions, optional database password/encryption, and read-only profile guardrails.',
    resultRenderers: ['document', 'table', 'json', 'schema', 'raw'],
    capabilities: [
      'supports_document_view',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_local_database_creation',
      'supports_admin_operations',
      'supports_index_management',
      'supports_import_export',
      'supports_backup_restore',
    ],
    baselineFeatures: [
      'Open/create local LiteDB file',
      'Collection/document/index CRUD',
      'Query editor',
      'Import/export',
    ],
    advancedFeatures: [
      'Password/encryption handling',
      'Schema sampling',
      'File backup workflow',
      'Collection compaction status',
      'Guarded checkpoint and compact previews',
    ],
    localDatabase: {
      defaultExtension: 'db',
      extensions: ['db', 'litedb'],
      canCreateEmpty: true,
      canCreateStarter: false,
    },
    diagnosticFeatures: [
      'File accessibility checks',
      'Index and collection size readouts',
      'Read-only file warnings',
      'Schema drift samples',
    ],
    analyticsSignals: [
      'Collection document counts',
      'Index counts',
      'File size',
      'Query duration',
    ],
  } satisfies DatastoreFeatureBacklogEntry
