import type { DatastoreFeatureBacklogEntry } from '../datastore-roadmap'
import { graphRenderers } from './common'

export const NEO4J_DATASTORE_FEATURE = {
    engine: 'neo4j',
    displayName: 'Neo4j',
    family: 'graph',
    maturity: 'beta',
    defaultLanguage: 'cypher',
    queryLanguages: ['cypher'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Bolt driver connection',
      'Neo4j URI with TLS and auth',
    ],
    defaultPort: 7687,
    managementModel: 'Property graph databases with nodes, relationships, labels, relationship types, indexes, constraints, users, roles, privileges, and databases.',
    queryModel: 'Cypher editor plus visual graph pattern builder and schema-aware templates.',
    presentationModel: 'Graph visualization, paths, tables, JSON, EXPLAIN/PROFILE plans, and metrics.',
    securityModel: 'Neo4j users, roles, privileges, database access, TLS, read-only profiles, and guarded writes.',
    resultRenderers: [...graphRenderers],
    capabilities: [
      'supports_graph_view',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_structure_visualization',
      'supports_vector_search',
    ],
    baselineFeatures: [
      'Database, node-label, relationship, index, and constraint browser',
      'Cypher editor',
      'Graph renderer',
      'Saved graph queries and exports',
    ],
    advancedFeatures: [
      'EXPLAIN/PROFILE operator plan',
      'Role/security browser',
      'GDS workflow hooks',
      'Vector index support',
    ],
    diagnosticFeatures: [
      'Operator plan visualization',
      'DB hits and row counts',
      'Privilege-aware disabled writes',
      'Graph rendering limits',
    ],
    analyticsSignals: [
      'DB hits and allocated memory',
      'Rows per plan operator',
      'Node and relationship counts',
      'Query duration',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const NEPTUNE_DATASTORE_FEATURE = {
    engine: 'neptune',
    displayName: 'Amazon Neptune',
    family: 'graph',
    maturity: 'beta',
    defaultLanguage: 'gremlin',
    queryLanguages: ['gremlin', 'sparql', 'cypher'],
    connectionModes: ['cloud-iam', 'cloud-sdk', 'connection-string'],
    primaryConnectionMechanisms: [
      'Gremlin/openCypher/SPARQL endpoints',
      'AWS SigV4/IAM through SDK or signed HTTP',
    ],
    defaultPort: 8182,
    managementModel: 'Managed graph clusters with Gremlin, openCypher, and SPARQL endpoints, cluster status, queries, bulk loader jobs, IAM, and CloudWatch metrics.',
    queryModel: 'Language-specific editors with graph/RDF result rendering and status/cancel controls.',
    presentationModel: 'Graph paths, RDF triples/tables, JSON, explain/profile output, loader status, and CloudWatch charts.',
    securityModel: 'AWS IAM/SigV4, VPC/network security, TLS, endpoint auth, and permission-aware cloud actions.',
    resultRenderers: [...graphRenderers, 'metrics'],
    capabilities: [
      'supports_graph_view',
      'supports_result_snapshots',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_query_cancellation',
      'supports_cloud_iam',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Gremlin, openCypher, and SPARQL editors',
      'Graph and RDF renderers',
      'Query status and cancel controls',
      'Cluster status browser',
    ],
    advancedFeatures: [
      'Gremlin/openCypher/SPARQL explain/profile',
      'CloudWatch metrics',
      'Bulk loader workflows',
      'IAM policy explanations',
    ],
    diagnosticFeatures: [
      'Explain/profile renderer',
      'Running query cancellation',
      'Loader job status',
      'CloudWatch dashboards',
    ],
    analyticsSignals: [
      'Query duration',
      'Engine CPU and memory',
      'Gremlin requests and errors',
      'Loader throughput',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const ARANGO_DATASTORE_FEATURE = {
    engine: 'arango',
    displayName: 'ArangoDB',
    family: 'graph',
    maturity: 'beta',
    defaultLanguage: 'aql',
    queryLanguages: ['aql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'ArangoDB HTTP API',
      'Connection URL with JWT/basic auth',
    ],
    defaultPort: 8529,
    managementModel: 'Multi-model databases with document collections, edge collections, named graphs, indexes, users, permissions, and services.',
    queryModel: 'AQL editor, collection/document/edge browser, and graph pattern helpers.',
    presentationModel: 'Documents, graph views, tables, AQL explain/profile plans, and metrics.',
    securityModel: 'Users, database and collection permissions, JWT/basic auth, TLS, and read-only profile guardrails.',
    resultRenderers: ['document', 'graph', 'table', 'json', 'plan', 'profile'],
    capabilities: [
      'supports_document_view',
      'supports_graph_view',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Collection, document, edge, and graph browser',
      'AQL editor',
      'Index CRUD',
      'Graph and document result renderers',
    ],
    advancedFeatures: [
      'AQL explain/profile plan charts',
      'User/database/collection permission viewer',
      'Foxx/service admin later',
      'Cluster health panels',
    ],
    diagnosticFeatures: [
      'AQL plan visualization',
      'Profile stage timing',
      'Permission-aware actions',
      'Cluster metrics',
    ],
    analyticsSignals: [
      'Execution time and scanned rows',
      'Plan node estimates',
      'Collection counts and sizes',
      'Cluster request metrics',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const JANUSGRAPH_DATASTORE_FEATURE = {
    engine: 'janusgraph',
    displayName: 'JanusGraph',
    family: 'graph',
    maturity: 'beta',
    defaultLanguage: 'gremlin',
    queryLanguages: ['gremlin'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Gremlin Server/WebSocket endpoint',
      'Backend-aware connection profile for storage and index services',
    ],
    defaultPort: 8182,
    managementModel: 'Distributed graph layer over storage/index backends with schema, property keys, labels, composite/mixed indexes, and index lifecycle state.',
    queryModel: 'Gremlin editor and graph renderer, with management API workflows for schema and index lifecycle.',
    presentationModel: 'Graph, table, JSON, schema/index status, backend health, and profile-like metrics where available.',
    securityModel: 'Gremlin endpoint auth, backend-specific auth, network ACLs, TLS, and guarded schema/index operations.',
    resultRenderers: [...graphRenderers, 'metrics'],
    capabilities: [
      'supports_graph_view',
      'supports_schema_browser',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Schema, index, property, and label browser',
      'Gremlin editor',
      'Graph renderer',
      'Backend health summary',
    ],
    advancedFeatures: [
      'Index lifecycle and reindex status',
      'Mixed-index operations',
      'Backend health drilldown',
      'Schema management workflows',
    ],
    diagnosticFeatures: [
      'Index status panels',
      'Backend health readouts',
      'Traversal timing where available',
      'Guarded schema mutations',
    ],
    analyticsSignals: [
      'Traversal duration',
      'Index lifecycle state',
      'Backend latency',
      'Vertex and edge sample counts',
    ],
  } satisfies DatastoreFeatureBacklogEntry
