import type { DatastoreFeatureBacklogEntry } from '../datastore-roadmap'
import { keyValueRenderers } from './common'

export const REDIS_DATASTORE_FEATURE = {
    engine: 'redis',
    displayName: 'Redis',
    family: 'keyvalue',
    maturity: 'mvp',
    defaultLanguage: 'redis',
    queryLanguages: ['redis', 'text'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'RESP protocol driver',
      'Redis URI with TLS, username, and secret references',
    ],
    defaultPort: 6379,
    managementModel: 'In-memory data structures with keys, types, TTLs, streams, modules, ACLs, INFO, SLOWLOG, memory, latency, and cluster topology.',
    queryModel: 'Command console plus key browser, SCAN builder, and type-aware editors for strings, hashes, lists, sets, sorted sets, streams, JSON, and search modules.',
    presentationModel: 'Key-value/type views, raw command output, INFO/SLOWLOG metrics, stream entries, and charts.',
    securityModel: 'ACL users/categories, TLS, passwords, read-only profiles, and guarded write/delete/flush commands.',
    resultRenderers: [...keyValueRenderers],
    capabilities: [
      'supports_key_browser',
      'supports_ttl_management',
      'supports_result_snapshots',
      'supports_streaming_results',
      'supports_admin_operations',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_vector_search',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Key browser with SCAN',
      'GET/HGETALL and type-aware editors',
      'Set/remove TTL',
      'Delete and rename keys with guardrails',
    ],
    advancedFeatures: [
      'Memory, latency, commandstats, and hit-rate charts',
      'ACL viewer',
      'Streams support',
      'JSON/Search module support',
    ],
    diagnosticFeatures: [
      'INFO dashboards',
      'SLOWLOG panel',
      'Memory usage inspection',
      'ACL-aware disabled commands',
    ],
    analyticsSignals: [
      'Memory usage and evictions',
      'Ops/sec and command stats',
      'Keyspace hits/misses',
      'Latency percentiles',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const VALKEY_DATASTORE_FEATURE = {
    engine: 'valkey',
    displayName: 'Valkey',
    family: 'keyvalue',
    maturity: 'beta',
    defaultLanguage: 'redis',
    queryLanguages: ['redis', 'text'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'RESP protocol driver',
      'Valkey/Redis-compatible URI',
    ],
    defaultPort: 6379,
    managementModel: 'Redis-compatible in-memory data structures with keys, TTL, ACLs, INFO, SLOWLOG, cluster topology, and module-aware extension points.',
    queryModel: 'Redis-compatible command console, key browser, SCAN builder, and type-aware editors.',
    presentationModel: 'Key-value/type output, raw command output, INFO/SLOWLOG metrics, and charts.',
    securityModel: 'ACL users/categories, TLS, secret references, read-only profiles, and guarded write/delete/flush commands.',
    resultRenderers: [...keyValueRenderers],
    capabilities: [
      'supports_key_browser',
      'supports_ttl_management',
      'supports_result_snapshots',
      'supports_streaming_results',
      'supports_admin_operations',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Redis-compatible key browser',
      'SCAN, GET, HGETALL, and type-aware editors',
      'TTL management',
      'Delete and rename with guardrails',
    ],
    advancedFeatures: [
      'Memory, latency, commandstats, and hit-rate charts',
      'ACL viewer',
      'Streams support',
      'Cluster topology',
    ],
    diagnosticFeatures: [
      'INFO dashboards',
      'SLOWLOG panel',
      'Memory usage inspection',
      'ACL-aware disabled commands',
    ],
    analyticsSignals: [
      'Memory usage and evictions',
      'Ops/sec and command stats',
      'Keyspace hits/misses',
      'Latency percentiles',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const MEMCACHED_DATASTORE_FEATURE = {
    engine: 'memcached',
    displayName: 'Memcached',
    family: 'keyvalue',
    maturity: 'beta',
    defaultLanguage: 'text',
    queryLanguages: ['text'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Memcached text or binary protocol',
      'Server list with optional SASL credentials',
    ],
    defaultPort: 11211,
    managementModel: 'Ephemeral cache nodes with simple keys, values, TTL, counters, slabs, item stats, and optional SASL.',
    queryModel: 'Command/action forms for get, gets, set, delete, touch, incr, decr, stats, and known-key lookup.',
    presentationModel: 'Key-value output, raw stats, slab dashboards, hit-rate charts, and eviction panels.',
    securityModel: 'Network ACLs, SASL where available, read-only profiles, and guarded mutation commands.',
    resultRenderers: [...keyValueRenderers],
    capabilities: [
      'supports_result_snapshots',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_admin_operations',
    ],
    baselineFeatures: [
      'Server stats',
      'Get/set/delete/incr/decr',
      'Known-key lookup',
      'TTL touch previews',
    ],
    advancedFeatures: [
      'Slab dashboards',
      'Hit-rate dashboards',
      'Eviction charts',
      'Item-size analysis',
      'Guarded stats reset and cache flush previews',
    ],
    diagnosticFeatures: [
      'Stats panels',
      'Slab and eviction readouts',
      'Network ACL warnings',
      'Mutation guardrails',
    ],
    analyticsSignals: [
      'Get hits/misses',
      'Evictions and reclaimed items',
      'Bytes used',
      'Connection counts',
    ],
  } satisfies DatastoreFeatureBacklogEntry
