import type { DatastoreFeatureBacklogEntry } from '../datastore-roadmap'

export const ELASTICSEARCH_DATASTORE_FEATURE = {
    engine: 'elasticsearch',
    displayName: 'Elasticsearch',
    family: 'search',
    maturity: 'beta',
    defaultLanguage: 'query-dsl',
    queryLanguages: ['query-dsl', 'esql', 'sql', 'json'],
    connectionModes: ['native', 'connection-string', 'cloud-iam'],
    primaryConnectionMechanisms: [
      'Elasticsearch HTTP API',
      'Elastic Cloud endpoint/API key',
    ],
    defaultPort: 9200,
    managementModel: 'Search/analytics/vector cluster with indices, data streams, mappings, templates, aliases, ILM, snapshots, shards, roles, and privileges.',
    queryModel: 'Query DSL editor, ES|QL/SQL editors, and visual search/filter/aggregation builder.',
    presentationModel: 'Search hits, aggregations, charts, mappings, explain/profile output, shard/segment stats, and vector-search results.',
    securityModel: 'RBAC users/roles, API keys, index privileges, TLS, cloud auth, read-only profiles, and guarded destructive index actions.',
    resultRenderers: ['searchHits', 'json', 'table', 'chart', 'plan', 'profile', 'metrics'],
    capabilities: [
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_cloud_iam',
      'supports_import_export',
      'supports_backup_restore',
      'supports_vector_search',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Typed HTTP, Elastic Cloud, API key, default-index, TLS, and timeout connection options',
      'Cluster, index, data stream, and mapping browser',
      'Query DSL editor',
      'Search hits and aggregation charts',
      'Index template and alias viewer',
    ],
    advancedFeatures: [
      'Explain/profile renderer',
      'Cluster, shard, segment, lifecycle, ingestion, and security posture panels',
      'Role/index privilege viewer',
      'Guarded force-merge, reindex, template, pipeline, ILM, task, snapshot, and restore previews',
      'Live HTTPS/cloud auth remains planned after the typed option contract',
    ],
    diagnosticFeatures: [
      'Profile tree',
      'Explain output',
      'Shard/segment dashboards',
      'Privilege-aware index actions',
    ],
    analyticsSignals: [
      'Hits, took, and timed_out',
      'Aggregation buckets',
      'Shard failures',
      'Index size and segment counts',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const OPENSEARCH_DATASTORE_FEATURE = {
    engine: 'opensearch',
    displayName: 'OpenSearch',
    family: 'search',
    maturity: 'beta',
    defaultLanguage: 'query-dsl',
    queryLanguages: ['query-dsl', 'sql', 'json'],
    connectionModes: ['native', 'connection-string', 'cloud-iam'],
    primaryConnectionMechanisms: [
      'OpenSearch HTTP API',
      'Managed OpenSearch endpoint with SigV4 or basic auth',
    ],
    defaultPort: 9200,
    managementModel: 'Elasticsearch-derived search/analytics cluster with indices, mappings, data streams, Dashboards plugins, security plugin, ISM, shards, and snapshots.',
    queryModel: 'Query DSL editor, SQL plugin editor where available, and visual search/filter/aggregation builder.',
    presentationModel: 'Search hits, aggregations, charts, mappings, profile output, plugin metrics, and shard stats.',
    securityModel: 'Security plugin users/roles/tenants, index privileges, SigV4/IAM on managed services, TLS, and guarded index actions.',
    resultRenderers: ['searchHits', 'json', 'table', 'chart', 'plan', 'profile', 'metrics'],
    capabilities: [
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_cloud_iam',
      'supports_import_export',
      'supports_backup_restore',
      'supports_vector_search',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Typed HTTP, managed endpoint, AWS SigV4, default-index, TLS, and timeout connection options',
      'Cluster, index, data stream, and mapping browser',
      'Query DSL editor',
      'Search hits and aggregation charts',
      'Separate adapter/version detection',
    ],
    advancedFeatures: [
      'Plugin-aware security browser',
      'Performance Analyzer panels',
      'Index State Management posture and guarded update previews',
      'Guarded force-merge, reindex, pipeline, task, snapshot, and restore previews',
      'Live HTTPS/SigV4 execution remains planned after the typed option contract',
    ],
    diagnosticFeatures: [
      'Profile tree',
      'Shard and segment dashboards',
      'Performance Analyzer metrics',
      'Security plugin permission explanations',
    ],
    analyticsSignals: [
      'Hits, took, and shard failures',
      'Aggregation buckets',
      'Index size and segment counts',
      'Plugin metrics',
    ],
  } satisfies DatastoreFeatureBacklogEntry
