import type { DatastoreFeatureBacklogEntry } from '../datastore-roadmap'
import { CLOUD_SECURITY, SQL_ADMIN, SQL_CORE, tableSchemaPlan } from './common'

export const POSTGRESQL_DATASTORE_FEATURE = {
    engine: 'postgresql',
    displayName: 'PostgreSQL',
    family: 'sql',
    maturity: 'mvp',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Native PostgreSQL protocol through a driver',
      'PostgreSQL connection string with vault-backed secrets',
    ],
    defaultPort: 5432,
    managementModel: 'Relational catalogs with databases, schemas, tables, views, functions, extensions, roles, grants, locks, and sessions.',
    queryModel: 'SQL editor first, with a visual schema/table/filter builder for common SELECT, DDL, index, and row-editing workflows.',
    presentationModel: 'Tabular rows, schema details, compact storage/index/security/activity panels, JSON EXPLAIN plans, profile output, metrics, and chart-ready statistics.',
    securityModel: 'Database roles, memberships, grants, SSL modes, read-only profiles, and production guardrails determine which actions are enabled.',
    resultRenderers: [...tableSchemaPlan],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_transactions',
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_streaming_results',
      'supports_structure_visualization',
      'supports_backup_restore',
      'supports_vector_search',
    ],
    baselineFeatures: [
      'Connect and test profiles',
      'Browse databases, schemas, tables, views, functions, indexes, and extensions',
      'Create/drop tables, add/drop columns, add/drop indexes, and edit rows',
      'SQL editor with saved queries, result snapshots, export, pagination, and streaming',
    ],
    advancedFeatures: [
      'EXPLAIN JSON renderer and guarded EXPLAIN ANALYZE',
      'Locks, sessions, and blocking tree views',
      'pg_stat* panels for table, index, and query health',
      'Vacuum, analyze, reindex, and maintenance helpers',
    ],
    diagnosticFeatures: [
      'Plan visualization',
      'Query profile comparison',
      'Query cancellation',
      'Permission-aware disabled DDL/DML actions',
    ],
    analyticsSignals: [
      'Rows returned and execution duration',
      'Shared block reads/hits and temp IO when available',
      'Table/index bloat and vacuum age',
      'Lock waits and active session counts',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const COCKROACHDB_DATASTORE_FEATURE = {
    engine: 'cockroachdb',
    displayName: 'CockroachDB',
    family: 'sql',
    maturity: 'mvp',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string', 'cloud-iam'],
    primaryConnectionMechanisms: [
      'PostgreSQL-compatible wire protocol through a driver',
      'CockroachDB connection string with TLS and vault-backed secrets',
      'Managed CockroachDB Cloud identity or certificate-based profiles where available',
    ],
    defaultPort: 26257,
    managementModel: 'Distributed SQL catalogs with databases, schemas, tables, indexes, constraints, ranges, regions, jobs, sessions, contention, roles, and grants.',
    queryModel: 'SQL editor first, with guarded DDL/table/index builders and Cockroach-specific SHOW/crdb_internal diagnostic templates.',
    presentationModel: 'Tabular rows, schema details, compact table/cluster/locality/job/contention/security posture panels, distributed SQL plans, EXPLAIN ANALYZE profiles, jobs, contention, latency metrics, and chart-ready cluster signals.',
    securityModel: 'SQL users, roles, grants/default privileges, TLS/certificates, cloud IAM signals, read-only profiles, and production guardrails for DDL/admin operations.',
    resultRenderers: [...tableSchemaPlan, 'series'],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      ...CLOUD_SECURITY,
      'supports_transactions',
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_streaming_results',
      'supports_structure_visualization',
      'supports_backup_restore',
      'supports_import_export',
    ],
    baselineFeatures: [
      'Connect through pgwire, connection strings, or cloud identity profiles',
      'Browse databases, schemas, tables, columns, indexes, constraints, ranges, regions, jobs, sessions, roles, and grants',
      'SQL editor, row editing, guarded table/index/column operations, and saved query workflows',
      'Cockroach-specific SHOW helpers for roles, grants, jobs, cluster settings, and node status',
    ],
    advancedFeatures: [
      'Distributed EXPLAIN plan rendering and guarded EXPLAIN ANALYZE (DISTSQL)',
      'Contention, session, job, range, and node status panels',
      'Role, grant, and default privilege inspection',
      'Backup/restore and import/export operation plans with explicit confirmation',
      'Guarded jobs, ranges, regions, sessions, contention, zone configuration, backup, restore, and import previews',
    ],
    diagnosticFeatures: [
      'Plan visualization',
      'Query profile and contention analysis',
      'Job progress, latency, and node health dashboards',
      'Permission-aware disabled DDL, backup, restore, and admin actions',
    ],
    analyticsSignals: [
      'Execution duration, rows read, and rows returned',
      'Contention events and lock wait signals',
      'Job status/progress and range distribution',
      'Cluster/node liveness, latency, and SQL session counts',
    ],
    roadmapNotes: [
      'Use information_schema, pg_catalog, and supported SHOW statements by default; use production-supported crdb_internal objects only when permitted.',
      'Treat EXPLAIN ANALYZE and backup/restore as guarded operations because they execute workload or mutate cluster state.',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const SQLSERVER_DATASTORE_FEATURE = {
    engine: 'sqlserver',
    displayName: 'SQL Server / Azure SQL',
    family: 'sql',
    maturity: 'mvp',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string', 'cloud-iam'],
    primaryConnectionMechanisms: [
      'TDS driver connection',
      'ADO-style connection string',
      'Azure SQL with Entra identity as a planned cloud IAM path',
    ],
    defaultPort: 1433,
    managementModel: 'Relational catalogs with databases, schemas, tables, views, procedures, functions, indexes, logins, users, roles, DMVs, and Query Store.',
    queryModel: 'T-SQL editor plus visual table/schema builders for common SELECT and DDL tasks.',
    presentationModel: 'Tables, schema views, compact storage/index/workload/security/Agent posture panels, XML/JSON showplans, Query Store history, DMV metrics, and dashboard charts.',
    securityModel: 'Server logins, database users, roles, object grants, Entra identity, encrypted connections, and read-only profile guardrails.',
    resultRenderers: [...tableSchemaPlan],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      ...CLOUD_SECURITY,
      'supports_transactions',
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_structure_visualization',
      'supports_cost_estimation',
      'supports_backup_restore',
    ],
    baselineFeatures: [
      'Connect and browse database objects',
      'Schema/table/view/procedure/index browser',
      'Create/drop tables, add/drop columns and indexes',
      'T-SQL editor with saved queries, snapshots, and export',
    ],
    advancedFeatures: [
      'Estimated and actual execution plan rendering',
      'Query Store history and regressions',
      'DMV dashboards for waits, sessions, locks, and IO',
      'Role and permission inspection',
      'Guarded statistics refresh, index maintenance, Query Store workload, import/export, and backup previews',
    ],
    diagnosticFeatures: [
      'Showplan visualization',
      'Query Store drilldown',
      'Live session cancellation',
      'Permission-aware DDL enablement',
    ],
    analyticsSignals: [
      'CPU, duration, reads, writes, and row counts',
      'Wait categories and blocking sessions',
      'Query Store runtime stats',
      'Index usage and missing-index hints',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const MYSQL_DATASTORE_FEATURE = {
    engine: 'mysql',
    displayName: 'MySQL',
    family: 'sql',
    maturity: 'mvp',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Native MySQL protocol through a driver',
      'MySQL connection string with vault-backed password',
      'Typed SSL, socket, Cloud SQL socket, session, cache, and timeout profile options',
    ],
    defaultPort: 3306,
    managementModel: 'Relational schemas with tables, views, routines, indexes, foreign keys, accounts, host privileges, INFORMATION_SCHEMA, and performance_schema.',
    queryModel: 'SQL editor plus visual builders for SELECT filters, table structure edits, indexes, and row edits.',
    presentationModel: 'Tables, DESCRIBE/SHOW metadata, JSON/text plans, performance schema metrics, and charts.',
    securityModel: 'User@host accounts, grants, SSL mode, read-only profiles, and production-safe destructive-action blocks.',
    resultRenderers: [...tableSchemaPlan],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_transactions',
      'supports_visual_query_builder',
      'supports_streaming_results',
      'supports_structure_visualization',
      'supports_backup_restore',
    ],
    baselineFeatures: [
      'Table, column, index, foreign key, view, and routine browser',
      'Create/drop tables, add/drop columns, add/drop indexes, and edit rows',
      'DESCRIBE and SHOW helpers',
      'SQL editor with snapshots, pagination, and export',
    ],
    advancedFeatures: [
      'EXPLAIN and ANALYZE rendering',
      'Slow query and performance_schema panels',
      'User and privilege browser',
      'Engine/status panels',
      'Guarded CHECK, ANALYZE, OPTIMIZE, REPAIR, and event state previews',
    ],
    diagnosticFeatures: [
      'Plan table visualization',
      'Slow query review',
      'Performance schema summaries',
      'Privilege-aware disabled writes',
    ],
    analyticsSignals: [
      'Rows examined and rows returned',
      'Handler counters and temp table use',
      'Slow query counts',
      'Buffer pool and connection metrics',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const MARIADB_DATASTORE_FEATURE = {
    engine: 'mariadb',
    displayName: 'MariaDB',
    family: 'sql',
    maturity: 'mvp',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Native MySQL-compatible protocol',
      'MariaDB/MySQL connection string with vault-backed password',
    ],
    defaultPort: 3306,
    managementModel: 'MySQL-like schemas plus MariaDB roles, storage engines, optimizer traces, status variables, and ANALYZE behavior.',
    queryModel: 'SQL editor and MySQL-compatible visual builders, with MariaDB-specific explain/profile rendering where available.',
    presentationModel: 'Tables, schema metadata, text/JSON plans, engine/status metrics, and charts.',
    securityModel: 'User accounts, roles, grants, SSL, read-only profiles, and production-safe guardrails.',
    resultRenderers: [...tableSchemaPlan],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_transactions',
      'supports_visual_query_builder',
      'supports_streaming_results',
      'supports_structure_visualization',
      'supports_backup_restore',
    ],
    baselineFeatures: [
      'Table, column, index, foreign key, view, and routine CRUD',
      'SQL editor with DESCRIBE/SHOW shortcuts',
      'Role-aware metadata browser',
      'Saved queries, snapshots, pagination, and export',
    ],
    advancedFeatures: [
      'MariaDB-specific EXPLAIN and ANALYZE output',
      'Role management and grant inspection',
      'Storage engine and status dashboards',
      'Slow query analysis',
      'Guarded table maintenance and event state previews',
    ],
    diagnosticFeatures: [
      'Plan and optimizer output renderer',
      'Status variable charts',
      'Privilege-aware admin controls',
      'Slow query panels',
    ],
    analyticsSignals: [
      'Rows examined, rows sent, and temp tables',
      'Engine status counters',
      'Connections and thread cache metrics',
      'Index usage indicators',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const SQLITE_DATASTORE_FEATURE = {
    engine: 'sqlite',
    displayName: 'SQLite',
    family: 'sql',
    maturity: 'mvp',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['local-file', 'connection-string'],
    primaryConnectionMechanisms: [
      'Local database file',
      'SQLite URI connection string',
    ],
    managementModel: 'Embedded file database with tables, views, triggers, indexes, PRAGMA metadata, and file-level access controls.',
    queryModel: 'SQL editor, file open/create workflows, and visual builders for tables, indexes, views, triggers, and row edits.',
    presentationModel: 'Tables, schema metadata, compact local-file/PRAGMA posture panels, EXPLAIN QUERY PLAN rows, and export files.',
    securityModel: 'File-system permissions, optional application-level read-only mode, secret-free local profiles, and destructive-action guardrails.',
    resultRenderers: ['table', 'schema', 'json', 'plan', 'raw'],
    capabilities: [
      ...SQL_CORE,
      'supports_local_database_creation',
      'supports_admin_operations',
      'supports_index_management',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_import_export',
      'supports_backup_restore',
      'supports_structure_visualization',
    ],
    localDatabase: {
      defaultExtension: 'sqlite',
      extensions: ['sqlite', 'sqlite3', 'db'],
      canCreateEmpty: true,
      canCreateStarter: true,
    },
    baselineFeatures: [
      'Open and create local database files',
      'Create/drop tables, indexes, views, and triggers',
      'PRAGMA schema browser',
      'SQL editor with snapshots and export',
    ],
    advancedFeatures: [
      'EXPLAIN QUERY PLAN renderer',
      'Integrity check workflow',
      'Vacuum/analyze/optimize/reindex helpers',
      'Local backup/export',
    ],
    diagnosticFeatures: [
      'Query plan rows',
      'Integrity check output',
      'Database page/cache PRAGMAs',
      'Read-only file warnings',
    ],
    analyticsSignals: [
      'Page count and freelist count',
      'Execution duration',
      'Row counts',
      'Integrity check status',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const ORACLE_DATASTORE_FEATURE = {
    engine: 'oracle',
    displayName: 'Oracle',
    family: 'sql',
    maturity: 'beta',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Host/port/service-name, SID, TNS alias, Easy Connect, TCPS, and cloud wallet profiles',
      'Oracle connection string pass-through with wallet and secret references',
    ],
    defaultPort: 1521,
    managementModel: 'Enterprise relational catalogs with CDB/PDB containers, schemas, tables, indexes, sequences, packages, procedures, functions, scheduler objects, queues, storage, security, dictionary views, users, roles, profiles, and grants.',
    queryModel: 'SQL Query, PL/SQL Script, and Explain Plan modes with Oracle-native templates, bundled managed-driver execution, optional legacy SQLPlus execution, and guarded DDL/admin preview plans.',
    presentationModel: 'Tables, dictionary metadata, DBMS_XPLAN-style plans, SQL Monitor templates, session/wait metrics, storage/security diagnostics, and charts.',
    securityModel: 'Users, roles, object grants, system privileges, proxy users, wallets, TCPS, read-only profiles, and environment guardrails determine action availability.',
    resultRenderers: [...tableSchemaPlan],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_transactions',
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_structure_visualization',
      'supports_backup_restore',
    ],
    baselineFeatures: [
      'Bundled managed Oracle runtime with service name, SID, TNS alias, Easy Connect, TCPS, wallet paths, proxy user, administrative role, NLS, fetch, timeout, pool, and optional legacy SQLPlus settings',
      'Container, schema, table, view, materialized view, synonym, sequence, function, procedure, package, type, scheduler, queue, storage, and security object browser',
      'SQL/PLSQL editor with Oracle templates, saved queries, object inspection, and export planning',
      'Object grants, role/profile, and permission-aware disabled action surfaces',
    ],
    advancedFeatures: [
      'Table, package, procedure, function, type, sequence, synonym, materialized view, grant, compile, and explain operation previews',
      'EXPLAIN PLAN and DBMS_XPLAN renderer with guarded SQL Monitor/AWR/ASH-style templates',
      'Session, lock, wait, storage, Data Guard, RAC, Flashback, and scheduler diagnostics where permissions allow',
      'Package spec/body/dependency/compilation-error and PL/SQL workflow support',
    ],
    diagnosticFeatures: [
      'DBMS_XPLAN and SQL Monitor plan templates',
      'Session, lock, wait, and active-session analysis',
      'Tablespace, segment, quota, invalid-object, and compile-error views',
      'Permission-aware DBA/V$/GV$/AWR/ASH controls with warning rows instead of hard failures',
    ],
    analyticsSignals: [
      'Elapsed time, CPU, logical reads, and physical reads',
      'Wait events',
      'Segment and index stats',
      'Session counts',
    ],
    roadmapNotes: [
      'Oracle Database 19c+ uses the bundled managed runtime by default; SQLPlus is an explicit legacy fallback for older or specialized Oracle Net configurations.',
      'Use ALL_* and USER_* views by default; query DBA_*, V$, GV$, AWR/ASH, Data Guard, and RAC views only when permissions allow.',
      'Admin/destructive Oracle operations remain guarded previews until a later pass explicitly enables live execution.',
    ],
  } satisfies DatastoreFeatureBacklogEntry
