import type { DatastoreFeatureBacklogEntry } from '../datastore-roadmap'
import { SQL_ADMIN, SQL_CORE, seriesRenderers } from './common'

export const TIMESCALEDB_DATASTORE_FEATURE = {
    engine: 'timescaledb',
    displayName: 'TimescaleDB',
    family: 'timeseries',
    maturity: 'beta',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'PostgreSQL protocol through a driver',
      'PostgreSQL-compatible connection string',
    ],
    defaultPort: 5432,
    managementModel: 'PostgreSQL plus hypertables, chunks, compression, continuous aggregates, retention policies, and time-series jobs.',
    queryModel: 'SQL editor and chart-first visual query builder for time buckets, filters, aggregations, and retention/compression workflows.',
    presentationModel: 'Tables, chart-ready series, hypertable/chunk schema, plans, metrics, and dashboards.',
    securityModel: 'PostgreSQL roles/grants plus extension object permissions and read-only/production guardrails.',
    resultRenderers: ['series', 'chart', 'table', 'schema', 'plan', 'metrics'],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_backup_restore',
      'supports_time_series_charting',
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_streaming_results',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'All PostgreSQL baseline features',
      'Hypertable and chunk explorer',
      'Time-bucket query templates',
      'Chart-first result rendering',
    ],
    advancedFeatures: [
      'Continuous aggregate management',
      'Compression and retention workflows',
      'Chunk stats and policy status',
      'Time-series dashboards',
      'Guarded compression-policy, retention-policy, and continuous aggregate refresh previews',
    ],
    diagnosticFeatures: [
      'Chunk health panels',
      'Continuous aggregate freshness',
      'Plan/profile output',
      'Retention/compression policy warnings',
    ],
    analyticsSignals: [
      'Chunk size and row counts',
      'Compression ratio',
      'Continuous aggregate lag',
      'Query duration by time window',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const INFLUXDB_DATASTORE_FEATURE = {
    engine: 'influxdb',
    displayName: 'InfluxDB',
    family: 'timeseries',
    maturity: 'beta',
    defaultLanguage: 'influxql',
    queryLanguages: ['flux', 'influxql', 'sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'InfluxDB HTTP API with token',
      'Version-specific URL and org/bucket profile',
    ],
    defaultPort: 8086,
    managementModel: 'Time-series buckets/databases with measurements, fields, tags, retention, tasks, tokens, and version-specific query engines.',
    queryModel: 'Query editor for Flux, InfluxQL, or SQL by version plus visual measurement/tag/field builder.',
    presentationModel: 'Chart-ready series, tables, bucket metadata, cardinality, task/retention status, and metrics.',
    securityModel: 'Token scopes, org/bucket permissions, TLS, read-only profiles, and guarded write/import tasks.',
    resultRenderers: [...seriesRenderers],
    capabilities: [
      'supports_time_series_charting',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_permission_inspection',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_streaming_results',
    ],
    baselineFeatures: [
      'Bucket, measurement, field, and tag explorer',
      'Version-aware query editor',
      'Line protocol import',
      'Series and table renderers',
    ],
    advancedFeatures: [
      'Retention and task management',
      'Guarded retention update previews',
      'Cardinality analysis',
      'Dashboard-ready series',
      'v1/v2/v3 compatibility',
    ],
    diagnosticFeatures: [
      'Cardinality warnings',
      'Query profile where available',
      'Task/retention status',
      'Token permission explanations',
    ],
    analyticsSignals: [
      'Series cardinality',
      'Query duration',
      'Bucket storage',
      'Task success/failure counts',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const PROMETHEUS_DATASTORE_FEATURE = {
    engine: 'prometheus',
    displayName: 'Prometheus',
    family: 'timeseries',
    maturity: 'beta',
    defaultLanguage: 'promql',
    queryLanguages: ['promql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Prometheus HTTP API',
      'URL profile behind auth proxy or service mesh',
    ],
    defaultPort: 9090,
    managementModel: 'Metrics TSDB with series, labels, targets, rules, alerts, TSDB/head status, and optional auth handled outside core Prometheus.',
    queryModel: 'PromQL editor plus metric/label/range query builder for instant and range queries.',
    presentationModel: 'Range charts, instant vectors, tables, label/series metadata, alert/rule panels, and TSDB metrics.',
    securityModel: 'External auth proxy, network policy, TLS, read-only profiles, and warnings for expensive label/series queries.',
    resultRenderers: ['series', 'chart', 'table', 'metrics', 'json'],
    capabilities: [
      'supports_time_series_charting',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_import_export',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_streaming_results',
    ],
    baselineFeatures: [
      'PromQL editor',
      'Series, label, target, and rule browser',
      'Instant/range query rendering',
      'Chart and table output',
    ],
    advancedFeatures: [
      'Alerts, rules, and status panels',
      'TSDB/head stats',
      'Cardinality analysis previews',
      'Recording-rule insights',
      'Expensive query warnings',
    ],
    diagnosticFeatures: [
      'Target health dashboard',
      'Rule evaluation status',
      'TSDB/head stats',
      'Label cardinality warnings',
    ],
    analyticsSignals: [
      'Sample counts',
      'Query duration',
      'Target up/down state',
      'Rule evaluation duration',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const OPENTSDB_DATASTORE_FEATURE = {
    engine: 'opentsdb',
    displayName: 'OpenTSDB',
    family: 'timeseries',
    maturity: 'beta',
    defaultLanguage: 'opentsdb',
    queryLanguages: ['opentsdb', 'json'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'OpenTSDB HTTP API',
      'Telnet protocol for legacy workflows',
    ],
    defaultPort: 4242,
    managementModel: 'HBase-backed time-series store with metrics, tags, aggregators, downsampling, UID metadata, trees, and stats endpoints.',
    queryModel: 'Metric/tag query builder with aggregator and downsample controls plus raw API JSON.',
    presentationModel: 'Chart-ready series, tables, raw API output, stats panels, UID/tree metadata, and warnings.',
    securityModel: 'No native auth in many deployments, so DataPad++ should surface network ACL/auth-proxy warnings and read-only guardrails.',
    resultRenderers: [...seriesRenderers, 'raw'],
    capabilities: [
      'supports_time_series_charting',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_metrics_collection',
      'supports_import_export',
    ],
    baselineFeatures: [
      'Metric and tag explorer',
      'Query builder with aggregator and downsample controls',
      'Series chart rendering',
      'Raw API response view',
    ],
    advancedFeatures: [
      '/api/stats dashboards',
      'UID and tree management',
      'Guarded UID repair previews',
      'Network ACL warnings',
      'HBase backend status hooks',
    ],
    diagnosticFeatures: [
      'API stats panels',
      'Missing-auth warnings',
      'High-cardinality tag warnings',
      'UID/tree health checks',
    ],
    analyticsSignals: [
      'Returned datapoints',
      'Query duration',
      'API stats counters',
      'Metric/tag cardinality samples',
    ],
  } satisfies DatastoreFeatureBacklogEntry
