import type { DatastoreFeatureBacklogEntry } from '../datastore-roadmap'
import { CLOUD_SECURITY, SQL_ADMIN, SQL_CORE } from './common'

export const CLICKHOUSE_DATASTORE_FEATURE = {
    engine: 'clickhouse',
    displayName: 'ClickHouse',
    family: 'warehouse',
    maturity: 'beta',
    defaultLanguage: 'clickhouse-sql',
    queryLanguages: ['clickhouse-sql', 'sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'ClickHouse HTTP or native protocol',
      'Connection string with database/user/secret references',
    ],
    defaultPort: 8123,
    managementModel: 'Columnar OLAP databases with tables, materialized views, dictionaries, system tables, RBAC, clusters, query logs, and metrics.',
    queryModel: 'ClickHouse SQL editor plus visual table/filter/aggregation builder and import/export workflows.',
    presentationModel: 'Tables, charts, schema metadata, EXPLAIN pipeline, query profile, system.query_log panels, and metrics dashboards.',
    securityModel: 'Users, roles, row policies, quotas, TLS, read-only profiles, and guarded mutations/DDL.',
    resultRenderers: ['table', 'chart', 'schema', 'plan', 'profile', 'metrics'],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_streaming_results',
      'supports_import_export',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Database, table, and materialized-view browser',
      'ClickHouse SQL editor',
      'Import/export workflows',
      'Chart-ready analytical results',
    ],
    advancedFeatures: [
      'EXPLAIN pipeline renderer',
      'system.query_log dashboards',
      'MergeTree parts and replica posture panels',
      'Metrics dashboards',
      'Guarded table optimization, TTL materialization, and freeze snapshot previews',
      'Cluster topology',
    ],
    diagnosticFeatures: [
      'Pipeline visualization',
      'Query log drilldown',
      'Memory and read-byte warnings',
      'Cluster health panels',
    ],
    analyticsSignals: [
      'Read rows/bytes and result rows',
      'Memory usage',
      'Query duration',
      'Selected parts and partitions',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const SNOWFLAKE_DATASTORE_FEATURE = {
    engine: 'snowflake',
    displayName: 'Snowflake',
    family: 'warehouse',
    maturity: 'beta',
    defaultLanguage: 'snowflake-sql',
    queryLanguages: ['snowflake-sql', 'sql'],
    connectionModes: ['native', 'connection-string', 'cloud-sdk'],
    primaryConnectionMechanisms: [
      'Snowflake driver connection',
      'Account URL with role, warehouse, authenticator, and secret references',
    ],
    defaultPort: 443,
    managementModel: 'Cloud warehouse with accounts, databases, schemas, tables, views, stages, warehouses, roles, grants, tasks, streams, shares, and query history.',
    queryModel: 'Snowflake SQL editor with active role/warehouse selector and visual table/query builder.',
    presentationModel: 'Tables, schema metadata, query profile/history, warehouse utilization, cost estimates, and charts.',
    securityModel: 'Role hierarchy, grants, warehouses, SSO/OAuth/key pair auth, network policies, masking policies, and permission-aware controls.',
    resultRenderers: ['table', 'schema', 'plan', 'profile', 'metrics', 'costEstimate', 'chart'],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_cloud_iam',
      'supports_cost_estimation',
      'supports_import_export',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Account, database, schema, table, stage, and warehouse browser',
      'Snowflake SQL editor',
      'Active role and warehouse selector',
      'Saved queries, snapshots, and export',
    ],
    advancedFeatures: [
      'Query history and profile',
      'Cost and warehouse utilization charts',
      'Guarded zero-copy clone and suspend/resume previews',
      'Tasks, streams, and shares',
      'Role/grant inspection',
    ],
    diagnosticFeatures: [
      'Query profile graph',
      'Warehouse utilization dashboard',
      'Credit/cost estimates',
      'Permission-aware disabled actions',
    ],
    analyticsSignals: [
      'Bytes scanned and rows produced',
      'Credits consumed',
      'Warehouse load',
      'Queue and execution time',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const BIGQUERY_DATASTORE_FEATURE = {
    engine: 'bigquery',
    displayName: 'BigQuery',
    family: 'warehouse',
    maturity: 'beta',
    defaultLanguage: 'google-sql',
    queryLanguages: ['google-sql', 'sql'],
    connectionModes: ['cloud-iam', 'cloud-sdk'],
    primaryConnectionMechanisms: [
      'Google Cloud SDK/Application Default Credentials',
      'Service account or OAuth identity with project/dataset IAM',
    ],
    managementModel: 'Serverless warehouse with projects, datasets, tables, views, jobs, reservations, scheduled queries, IAM, and INFORMATION_SCHEMA.',
    queryModel: 'GoogleSQL editor with dry-run byte estimate, visual dataset/table builder, and job workflow controls.',
    presentationModel: 'Tables, schema metadata, job history, dry-run cost estimates, INFORMATION_SCHEMA metrics, slot usage charts, and dashboards.',
    securityModel: 'Google IAM, dataset/table policy tags, OAuth/ADC/service accounts, read-only profiles, and guarded write/export jobs.',
    resultRenderers: ['table', 'schema', 'profile', 'metrics', 'costEstimate', 'chart', 'json'],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      ...CLOUD_SECURITY,
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_cost_estimation',
      'supports_import_export',
      'supports_streaming_results',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Project, dataset, table, and job browser',
      'GoogleSQL editor',
      'Dry-run byte estimate',
      'Saved queries, snapshots, and export',
    ],
    advancedFeatures: [
      'INFORMATION_SCHEMA.JOBS performance/cost dashboards',
      'Slot usage panels',
      'Guarded table copy previews',
      'Scheduled queries',
      'IAM explanation and permission-aware controls',
    ],
    diagnosticFeatures: [
      'Dry-run cost estimate',
      'Job timeline/profile',
      'Slot utilization dashboard',
      'Large scan warnings',
    ],
    analyticsSignals: [
      'Bytes processed and billed',
      'Slot milliseconds',
      'Job duration',
      'Estimated query cost',
    ],
  } satisfies DatastoreFeatureBacklogEntry
