import type { DatastoreFeatureBacklogEntry } from '../datastore-roadmap'

export const DYNAMODB_DATASTORE_FEATURE = {
    engine: 'dynamodb',
    displayName: 'DynamoDB',
    family: 'widecolumn',
    maturity: 'beta',
    defaultLanguage: 'json',
    queryLanguages: ['json', 'sql'],
    connectionModes: ['cloud-iam', 'cloud-sdk'],
    primaryConnectionMechanisms: [
      'AWS SDK with IAM credentials or role assumption',
      'Endpoint override for local/test DynamoDB',
    ],
    defaultPort: 8000,
    managementModel: 'Serverless tables with partition/sort keys, items, GSIs, LSIs, TTL, streams, capacity mode, and CloudWatch metrics.',
    queryModel: 'Partition-key-first Query builder, Scan builder with warnings, guarded read-only PartiQL ExecuteStatement requests, and raw AWS API JSON.',
    presentationModel: 'Items as key-value/document rows, table/index metadata, consumed capacity, CloudWatch metrics, and cost charts.',
    securityModel: 'AWS IAM policies, resource ARNs, temporary credentials, SigV4, read-only profiles, and production scan/write guardrails.',
    resultRenderers: ['keyvalue', 'document', 'table', 'metrics', 'costEstimate'],
    capabilities: [
      'supports_document_view',
      'supports_key_browser',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_permission_inspection',
      'supports_cloud_iam',
      'supports_metrics_collection',
      'supports_cost_estimation',
      'supports_import_export',
      'supports_backup_restore',
      'supports_streaming_results',
    ],
    baselineFeatures: [
      'Typed local endpoint, AWS profile, static key, assume-role, and web-identity connection options',
      'Table and item browser',
      'Key-condition Query builder',
      'GSI/LSI viewer and add/drop GSI workflow',
      'TTL, streams, and backup viewer',
    ],
    advancedFeatures: [
      'Consumed capacity display',
      'CloudWatch throttle and latency dashboards',
      'Guarded capacity, TTL, stream, and backup previews',
      'Cost estimate panels',
      'Single-table modeling hints',
    ],
    diagnosticFeatures: [
      'Scan warning guardrails',
      'Hot partition indicators',
      'Consumed capacity charts',
      'IAM permission explanations',
    ],
    analyticsSignals: [
      'Read/write capacity units',
      'Throttled requests',
      'Returned item count and scanned count',
      'Estimated request cost',
    ],
  } satisfies DatastoreFeatureBacklogEntry

export const CASSANDRA_DATASTORE_FEATURE = {
    engine: 'cassandra',
    displayName: 'Cassandra',
    family: 'widecolumn',
    maturity: 'beta',
    defaultLanguage: 'cql',
    queryLanguages: ['cql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Cassandra native protocol driver',
      'Contact-point connection profile with TLS and credentials',
    ],
    defaultPort: 9042,
    managementModel: 'Distributed wide-column keyspaces with tables, UDTs, indexes, materialized views, roles, permissions, tracing, compaction, and repair state.',
    queryModel: 'CQL editor plus partition-key-aware visual builder that keeps users inside Cassandra query rules.',
    presentationModel: 'Tabular results, keyspace/table metadata, tracing spans, nodetool/JMX metrics, and charts.',
    securityModel: 'Roles, permissions, TLS, auth providers, and guardrails for token-range scans and admin operations.',
    resultRenderers: ['table', 'schema', 'metrics', 'plan', 'profile'],
    capabilities: [
      'supports_schema_browser',
      'supports_result_snapshots',
      'supports_visual_query_builder',
      'supports_admin_operations',
      'supports_index_management',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_backup_restore',
      'supports_streaming_results',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Typed contact-point, secure-bundle, TLS, consistency, retry, and load-balancing connection options',
      'Keyspace, table, type, index, and materialized-view browser',
      'CQL editor',
      'Partition-key visual query builder',
      'Role and permission browser',
      'Contract-backed cqlsh COPY import/export and nodetool snapshot plans',
    ],
    advancedFeatures: [
      'SAI/index guidance',
      'Query tracing',
      'Partition model, tombstone, and cluster health panels',
      'Nodetool/JMX readouts',
      'Repair and compaction status',
      'Guarded export, snapshot, and restore plan previews',
    ],
    diagnosticFeatures: [
      'Tracing timeline',
      'Compaction/repair panels',
      'Partition scan warnings',
      'Permission-aware admin actions',
    ],
    analyticsSignals: [
      'Read/write latency',
      'Tombstone warnings',
      'SSTable and compaction metrics',
      'Coordinator and replica timing',
    ],
  } satisfies DatastoreFeatureBacklogEntry
